/* ========================================
   Daily Motion Graphics Picks — Data
   ----------------------------------------
   このファイルは毎朝10時のスケジュールタスクが自動更新します。
   手動でも編集可能（フォーマットを保つこと）。

   各エントリのスキーマ:
   {
     id: "YYYY-MM-DD-jp-01",       // ユニークID
     date: "YYYY-MM-DD",           // ピックアップ日
     region: "jp" | "global",       // 国内 / 海外
     title: "作品タイトル",
     creator: "制作者・スタジオ名",
     platform: "YouTube",          // YouTube / Vimeo / X / TikTok / Behance 等
     videoUrl: "https://...",      // 動画本体URL
     creatorUrl: "https://...",    // 制作者ページURL（任意）
     articleUrl: "",               // 関連記事URL（任意）
     publishedDate: "YYYY-MM-DD",  // 作品の公開日
     genre: ["MV", "モーショングラフィクス"],
     techniques: ["3DCG", "タイポグラフィ"],
     thumbnail: "https://...",     // サムネイルURL（YouTube: https://img.youtube.com/vi/{ID}/mqdefault.jpg）
     notes: "注目ポイント（2-3行）"
   }
   ======================================== */

window.picksData = [
  // ===== 2026-05-26 MOTION =====
  {
    id: "2026-05-26-jp-01",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "PAL CLOSET「パルクロ春一番 2026」Web CM",
    creator: "ong_",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=4zGPUmajdrQ",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2026-03-01",
    genre: ["CM"],
    techniques: ["キネティックタイポ", "タイポグラフィ", "作字"],
    thumbnail: "https://img.youtube.com/vi/4zGPUmajdrQ/mqdefault.jpg",
    notes: "ong_が手がけたパルコのレディースブランド「PAL CLOSET」春CMシリーズ最新作。文字が踊るように動くキネティックタイポグラフィで季節感と高揚感を演出。日本語のリズムとデザインを最大限に引き出すong_流モーション設計は国内CMモーションの最前線。"
  },
  {
    id: "2026-05-26-jp-02",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "GUNZE「読めない、GUNZE。」書道篇 — 130周年記念 Web CM",
    creator: "KOO-KI（空気株式会社）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=NJPwkBNe9U8",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://www.gunze.co.jp/corporate/news/2026/02/20260204001.html",
    publishedDate: "2026-02-04",
    genre: ["CM", "ブランディング"],
    techniques: ["作字", "日本語タイポ"],
    thumbnail: "https://img.youtube.com/vi/NJPwkBNe9U8/mqdefault.jpg",
    notes: "グンゼ創業130周年キャンペーン「読めない、GUNZE。」書道篇。一流書道家の達筆で「グンゼ」を書き上げると、その美しい筆記体が逆に一般人には読みにくいという逆説を軽妙に描く。企業名の認知度という課題をコンセプチュアルな作字演出で解決した秀逸なCM。KOO-KIの遊び心あるアイデアと映像技術が光る。"
  },
  {
    id: "2026-05-26-jp-03",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "GUNZE「読めない、GUNZE。」視力検査篇 — 130周年記念 Web CM",
    creator: "KOO-KI（空気株式会社）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LYVMJH47z84",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://www.gunze.co.jp/corporate/news/2026/02/20260204001.html",
    publishedDate: "2026-02-04",
    genre: ["CM", "ブランディング"],
    techniques: ["作字", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/LYVMJH47z84/mqdefault.jpg",
    notes: "同キャンペーンの視力検査篇。眼科の視力検査表スタイルでGUNZEの文字を提示し「読めますか？」と問いかけるユーモラスな演出。書道篇とは正反対のアプローチで同テーマを別角度から攻める二本構成が巧妙。日本語タイポグラフィの認知的面白さを極めたキャンペーンCMの好例。"
  },
  {
    id: "2026-05-26-jp-04",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "にじさんじ「あるてぃめっとくりえいたーず」始動映像",
    creator: "ong_（モーションデザイン） / にじさんじ",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LzxHoNVbgz0",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2026-04-01",
    genre: ["ブランディング", "タイトル/OP"],
    techniques: ["キネティックタイポ", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/LzxHoNVbgz0/mqdefault.jpg",
    notes: "VTuberグループ「にじさんじ」の新クリエイティブ企画「あるてぃめっとくりえいたーず」始動映像。ong_がDirection・Design・Motion Designを担当したオープニング映像を含む。メンバー自身が動画企画・制作を担うというコンセプトに合わせ、軽快かつ遊び心あるモーション演出を採用。2026年4月1日に公開された話題作。"
  },
  {
    id: "2026-05-26-jp-05",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "サントリー 優しい麦茶「小島よしお リサイクルリサイタル」リリックモーション",
    creator: "ong_ / CHOCOLATE Inc. / GEEK PICTURES Inc.",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=UWdYZWPkHVU",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "https://eizo100.jp/video/89686",
    publishedDate: "2024-07-11",
    genre: ["リリックモーション", "CM"],
    techniques: ["リリックモーション", "キネティックタイポ", "作字"],
    thumbnail: "https://img.youtube.com/vi/UWdYZWPkHVU/mqdefault.jpg",
    notes: "小島よしおの代名詞ネタをリサイクルをテーマにリサイタル化したサントリー優しい麦茶のリリックモーション。ong_がポップかつリズミカルなキネティックタイポグラフィを設計し、いつも以上にクールな小島よしおを演出。日本語リリックモーションの手本として国内モーションデザインコミュニティで高く評価された一作。"
  },
  {
    id: "2026-05-26-global-01",
    date: "2026-05-26",
    type: "video",
    region: "global",
    title: "Google I/O 2026 — TPU Training Day",
    creator: "Nexus Studios / Laurie Rowan × Google",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=dhI4djOVEmI",
    creatorUrl: "https://nexusstudios.com/",
    articleUrl: "https://lbbonline.com/news/Google-TPU-Chip-Puppets-Training-Montage",
    publishedDate: "2026-05-19",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/dhI4djOVEmI/mqdefault.jpg",
    notes: "Google I/O 2026基調講演オープニングフィルム。AIチップ「Timmy」が80年代スポーツ映画のトレーニングモンタージュスタイルで大舞台に挑む姿を描く。パイプクリーナー・厚紙パペット・CGI・GoogleのGenAIを融合したハイブリッドパイプラインをNexus Studiosが開発。ハンドメイドの温かみとテクノロジーの掛け合わせが絶妙な2026年5月公開の話題作。"
  },
  {
    id: "2026-05-26-global-02",
    date: "2026-05-26",
    type: "video",
    region: "global",
    title: "Canva — Affinity: Creative Freedom (Zero Bucks Given)",
    creator: "ManvsMachine",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1132555160",
    creatorUrl: "https://mvsm.com/",
    articleUrl: "https://www.stashmedia.tv/zero-bucks-given-manvsmachine-keeps-it-kinetic-for-canva/",
    publishedDate: "2026-03-15",
    genre: ["CM", "ブランディング"],
    techniques: ["キネティックタイポ", "3DCG", "2Dアニメーション"],
    thumbnail: "https://vumbnail.com/1132555160.jpg",
    notes: "CanvaがデザインツールAffinityを無料化するに際し制作したローンチブランドフィルム。ManvsMachineが3D・2Dモーション・キネティックタイポ・手描きイラストを疾走感ある映像に結合。クリエイターが制約なく創造できる世界への熱いメッセージを、プロダクトデモと感情的ストーリーテリングを絶妙に組み合わせて表現した2026年上半期の傑作CM。"
  },
  {
    id: "2026-05-26-global-03",
    date: "2026-05-26",
    type: "video",
    region: "global",
    title: "Alien: Earth — Gestation Promo Film",
    creator: "Tendril / FX Networks",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1163787073",
    creatorUrl: "https://tendril.studio/",
    articleUrl: "https://www.stashmedia.tv/gestation-of-horror-tendril-and-fx-launch-alien-earth/",
    publishedDate: "2026-03-03",
    genre: ["CM", "3DCG", "VFX"],
    techniques: ["3DCG", "シミュレーション", "NPR"],
    thumbnail: "https://vumbnail.com/1163787073.jpg",
    notes: "FXドラマ「Alien: Earth」ローンチキャンペーンのプロモフィルム「Gestation」。TendrilがHoudiniで構築した三方向細胞分裂・拍動する臓器・流体器官などの有機的3DCGシミュレーションと、FX撮影のプラクティカルエフェクトを不可視の継ぎ目で融合。地球外生命体の誕生過程を生物学的精密さで描いたClio Award受賞作。"
  },
  {
    id: "2026-05-26-global-04",
    date: "2026-05-26",
    type: "video",
    region: "global",
    title: "OpenTable — Find a Restaurant You Love",
    creator: "Giant Ant (a BUCK company)",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1163448564",
    creatorUrl: "https://www.giantant.ca/",
    articleUrl: "https://roastbrief.us/opentable-taps-giant-ant-as-u-s-creative-agency-debuts-first-ever-animated-campaign-for-valentines-day/",
    publishedDate: "2026-02-14",
    genre: ["CM", "アニメーション"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://vumbnail.com/1163448564.jpg",
    notes: "Giant AntがOpenTableの初アニメーションブランドキャンペーン向けに制作。料理映像ではなく「なぜ人は集まるのか」という感情的動機を主題に、OpenTableのデータから抽出したインサイトを2Dアニメで可視化。温かみあるキャラクターアニメーションがブランドの本質を的確に伝える良質なストーリーテリングの好例。"
  },
  {
    id: "2026-05-26-global-05",
    date: "2026-05-26",
    type: "video",
    region: "global",
    title: "Doodles — The Stoodio (Featuring Pharrell Williams)",
    creator: "Golden Wolf",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=V5Kgh0YjAi0",
    creatorUrl: "https://www.goldenwolf.tv/",
    articleUrl: "https://www.stashmedia.tv/96548-2/",
    publishedDate: "2026-04-01",
    genre: ["ブランディング", "アニメーション"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/V5Kgh0YjAi0/mqdefault.jpg",
    notes: "Golden WolfがDoodlesのクリエイティブハブ「The Stoodio」プラットフォームのローンチに制作したブランドフィルム。最高ブランド責任者ファレル・ウィリアムスをフィーチャーし、誰でもオリジナルDoodlesアバターを作れる新世界を発表。Golden Wolf特有の高彩度・ポップアートスタイルの2Dキャラクターアニメーションが炸裂する一作。"
  },
  // ===== 2026-05-26 GRAPHIC JP =====
  {
    id: "2026-05-26-graphic-jp-01",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "作字(SAKUJI) — typography study",
    creator: "Kisuke Ohta",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/43665761/(SAKUJI)-typography-study",
    creatorUrl: "https://www.behance.net/kisuke",
    articleUrl: "",
    publishedDate: "2016-01-01",
    genre: ["タイポグラフィ"],
    techniques: ["作字", "日本語タイポ"],
    thumbnail: "https://i.pinimg.com/736x/f1/b2/1f/f1b21fbf1074ff5bd6c45ef182a4f9a7.jpg",
    notes: "東京のグラフィックデザイナー・Kisuke Ohtaによる作字スタイル研究の集大成。ゴシック・明朝・装飾的バリエーションまで漢字の骨格を解析・再構築し、無数の字体を展開する。書体設計と作字の境界を探る実験的アーカイブとして現在もPinterest上で国内外のデザイナーに広く参照され続けている定番作。"
  },
  {
    id: "2026-05-26-graphic-jp-02",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "KAGUWA — Japanese Black Tea Branding",
    creator: "Koyuki Inagaki",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/226119129/KAGUWA",
    creatorUrl: "https://www.behance.net/koyukiinagaki",
    articleUrl: "",
    publishedDate: "2025-05-17",
    genre: ["ブランディング", "パッケージ"],
    techniques: ["ミニマル", "日本語タイポ"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/672445226119129.6828ead9d29f0.jpg",
    notes: "東京在住デザイナーが手がけた日本産純粋紅茶ブランド「KAGUWA」のブランディング。ひらがなの曲線を想起させるロゴタイプが和と洋の均衡を象徴し、必要最小限の装飾で茶葉本来の香りを視覚化。小ぶりな缶とタグの造形と相まって、モダンな日本らしさを体現したパッケージデザイン。"
  },
  {
    id: "2026-05-26-graphic-jp-03",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "SENSE ISLAND/LAND 2024 — コミュニケーションデザイン",
    creator: "Flowplateaux (木村浩康 + 藤井かおり) / Panoramatiks",
    platform: "Flowplateaux",
    videoUrl: "https://flowplateaux.com/en/work/sense-island-land-2024_communication-design/",
    creatorUrl: "https://flowplateaux.com/en/",
    articleUrl: "",
    publishedDate: "2025-11-05",
    genre: ["ポスター", "ブランディング", "サインデザイン"],
    techniques: ["タイポグラフィ重視", "ミニマル"],
    thumbnail: "https://flowplateaux.com/wp-content/uploads/2025/10/SSL_FPX-1200x625.png",
    notes: "横須賀の没入型アートフェスティバル「SENSE ISLAND/LAND 2024」のコミュニケーションデザイン。モールス信号のリズムを基軸に、メディアと視距離で変容する柔軟なビジュアルシステムを構築。DFA Design for Asia 2025 Gold Award・東京ADC Award 2025・Japan Typography Annual 2026 審査員賞を達成した国内トップスタジオ作。"
  },
  {
    id: "2026-05-26-graphic-jp-04",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "田部井美奈「光と図形と、その周辺」",
    creator: "田部井美奈 / Mina Tabei",
    platform: "Ginza Graphic Gallery",
    videoUrl: "https://www.dnpfcp.jp/gallery/ggg/jp/00000848",
    creatorUrl: "https://www.instagram.com/mina_tabei/",
    articleUrl: "",
    publishedDate: "2025-09-05",
    genre: ["ポスター"],
    techniques: ["幾何学", "モノクロ", "ハイコントラスト"],
    thumbnail: "https://www.adfwebmagazine.jp/wp-content/uploads/2025/08/adf-web-magazine-mina-tabei-ggg-1.jpg",
    notes: "ギンザ・グラフィック・ギャラリー第409回企画展。2018年以来追求してきた実験作「光と図形」の最新シリーズを空間ごと体験できる形で発表。光と影・三次元の偶然性を二次元の紙面に定着させた独自の幾何学表現で、第28回亀倉雄策賞・JAGDA Award 2026をW受賞。"
  },
  {
    id: "2026-05-26-graphic-jp-05",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "GRAPHIC TRIAL 2025 -FIND-",
    creator: "大貫卓也 / 関本明子 / 吉本英樹 / 妹尾琢史 × TOPPAN",
    platform: "TOPPAN",
    videoUrl: "https://www.toppan.com/ja/joho/gainfo/graphictrial/2025/",
    creatorUrl: "https://www.toppan.com/ja/joho/gainfo/graphictrial/2025/creator/",
    articleUrl: "",
    publishedDate: "2025-04-12",
    genre: ["ポスター"],
    techniques: ["タイポグラフィ重視", "ハイコントラスト"],
    thumbnail: "",
    notes: "TOPPANと国内トップクリエイター4名が協働するポスター展覧会「グラフィックトライアル」第19回。テーマ「FIND」のもと、大貫卓也がレンチキュラー大判印刷の空間体験、関本明子がインク重ね刷りの色彩の謎を探究。活版・スクリーン・インクジェットなど最先端技術とグラフィックデザインが融合した印刷表現の最前線。"
  },
  // ===== 2026-05-26 GRAPHIC GLOBAL =====
  {
    id: "2026-05-26-graphic-global-01",
    date: "2026-05-26",
    type: "graphic",
    region: "global",
    title: "KAIJU/ROLL — Visual Identity & Branding Concept",
    creator: "Daria Vasileva",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/247714979/KAIJUROLL-Visual-Identity-Branding-Concept",
    creatorUrl: "",
    articleUrl: "",
    publishedDate: "2026-04-17",
    genre: ["ブランディング", "パッケージ"],
    techniques: ["ブルータリスト", "スイス・グリッド", "タイポグラフィ重視"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/6cade8247714979.69e2327738dc0.jpg",
    notes: "ポーランドのデザイナーによる寿司レストランの大胆なブランドコンセプト。「Zen」的な和の美学を意図的に覆し、日本ポップカルチャーの怪獣的カオスとエネルギーを体現。ブルータリスト×スイスグリッドの高コントラスト幾何学デザインが既存のJapanese food brandingを根底から再定義した刺激的な一作。"
  },
  {
    id: "2026-05-26-graphic-global-02",
    date: "2026-05-26",
    type: "graphic",
    region: "global",
    title: "Shibuya Punk Posters — Visual Series",
    creator: "Rafael Ribeiro de Michelli",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/237542071/Shibuya-Punk-Posters-Visual-Series",
    creatorUrl: "",
    articleUrl: "",
    publishedDate: "2025-10-29",
    genre: ["ポスター"],
    techniques: ["モノクロ", "ハイコントラスト", "コラージュ", "タイポグラフィ重視"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/hd_webp/69a59d237542071.69027a98e9f68.png",
    notes: "ブラジルのデザイナーが東京・渋谷の視覚的過剰とパンクの反骨精神を融合させた実験的ポスターシリーズ。白黒写真にラテン文字とカタカナタイポグラフィを重ね、ハーフトーンテクスチャとデジタルノイズで有機的な質感を生む。非対称グリッドと強烈なコントラストが「渋谷」というカオスを的確に体現する。"
  },
  {
    id: "2026-05-26-graphic-global-03",
    date: "2026-05-26",
    type: "graphic",
    region: "global",
    title: "Visual Identity Tool — Creative Week 2025",
    creator: "Amuki Estudio",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/230128037/Visual-Identity-Tool-Creative-Week-2025",
    creatorUrl: "",
    articleUrl: "",
    publishedDate: "2025-07-14",
    genre: ["ブランディング"],
    techniques: ["タイポグラフィ重視", "幾何学"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/a29fd4230128037.68b7126d1954d.jpg",
    notes: "スペインのスタジオがThe One Club for Creativity「Creative Week 2025」（NY）のために制作したVI。2つのパターンフォントと4つのディスプレイフォントからなる6書体システムをProcessingで生成するタイポグラフィツールとともに開発。幾何学グリッド上で無限にバリエーション展開できる書体システムが印刷物・グッズに横断展開される。"
  },
  {
    id: "2026-05-26-graphic-global-04",
    date: "2026-05-26",
    type: "graphic",
    region: "global",
    title: "Green-Wood Cemetery — Visual Identity",
    creator: "Pentagram / Abbott Miller",
    platform: "Pentagram",
    videoUrl: "https://www.pentagram.com/work/green-wood-cemetery",
    creatorUrl: "https://www.pentagram.com/",
    articleUrl: "",
    publishedDate: "2025-01-01",
    genre: ["ブランディング", "サインデザイン"],
    techniques: ["タイポグラフィ重視", "レトロ"],
    thumbnail: "",
    notes: "ペンタグラムがブルックリンの歴史的霊園グリーンウッドと新ビジターセンターのために設計したVIとサインシステム。墓碑・記念碑に刻まれた歴史的書体を源泉に持つカスタムタイポグラフィ、花輪モチーフから着想した二重Oのリガチャーが秀逸。追悼の厳粛さと文化的コミュニティとしての開放性が共存する、格調高いアイデンティティ設計。"
  },
  {
    id: "2026-05-26-graphic-global-05",
    date: "2026-05-26",
    type: "graphic",
    region: "global",
    title: "Graphic Design Trends 2026 Poster Series",
    creator: "Yaroslav Iakovlev",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/240332059/Graphic-Design-Trends-2026-Poster-Series",
    creatorUrl: "",
    articleUrl: "",
    publishedDate: "2025-12-12",
    genre: ["ポスター"],
    techniques: ["タイポグラフィ重視", "グリッチ", "コラージュ"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/6d5241240332059.693c0235669f4.jpg",
    notes: "スペイン・バレンシア在住のデザイナーが2026年のデザイントレンドを10作のポスターで体現するシリーズ。Punk Revival・Naive Design・Blueprint Design・Frutiger Aero・Distorted Photography・Type Collageなど多彩な潮流を一覧できる。ミニマリズムからの離脱と「叛乱・感情・再魔法化の衝突」を鮮烈なビジュアルで宣言する。"
  },
  // ===== 2026-05-22 GRAPHIC (cleared - articles only, will be re-populated via Run now with Pinterest-style sources) =====
  // ===== 2026-05-22 MOTION =====
  {
    id: "2026-05-22-jp-01",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "Nintendo Switch 2 – Overview Trailer",
    creator: "Nintendo",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=9flte56erE8",
    creatorUrl: "https://www.nintendo.co.jp/",
    articleUrl: "",
    publishedDate: "2025-01-16",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/9flte56erE8/mqdefault.jpg",
    notes: "任天堂が2025年1月16日にサプライズ公開したNintendo Switch 2の公式オーバービュートレーラー。実写とCGを組み合わせた洗練されたプロダクト映像で、Joy-Con 2の磁気アタッチメント・マウスモードなど新機能を直感的に伝える構成が見事。初日4800万再生を記録し、世界的ゲームハードローンチにおける映像コミュニケーション設計の模範例として高く評価された。"
  },
  {
    id: "2026-05-22-jp-02",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "米津玄師「IRIS OUT」Official Music Video",
    creator: "米津玄師 / 劇場版チェンソーマン レゼ篇",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LmZD-TU96q4",
    creatorUrl: "https://www.youtube.com/channel/UCUCeZaZeJbEYAAzvMgrKOPQ",
    articleUrl: "",
    publishedDate: "2025-09-15",
    genre: ["MV", "アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/LmZD-TU96q4/mqdefault.jpg",
    notes: "劇場版『チェンソーマン レゼ篇』主題歌。Spotify Japan史上最多ストリーム初日記録を更新し、2026年5月現在もBillboard JAPAN Hot Animation 1位をキープするロングラン。劇場映像とアニメーションの緩急あるカット割りと楽曲の疾走感が完璧に噛み合う。"
  },
  {
    id: "2026-05-22-jp-03",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "ヨルシカ「へび」OFFICIAL VIDEO",
    creator: "ヨルシカ / 佐藤美代",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=sf0QFJTvOLM",
    creatorUrl: "https://yorushika.com/",
    articleUrl: "https://realsound.jp/2025/02/post-1938409.html",
    publishedDate: "2025-01-17",
    genre: ["MV", "アニメーション"],
    techniques: ["ストップモーション", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/sf0QFJTvOLM/mqdefault.jpg",
    notes: "TVアニメ『チ。―地球の運動について―』新エンディングテーマ。アニメーター佐藤美代が手がけたサンドアニメーション＋ペインティング・オン・グラスによる繊細な映像。記憶と風景が砂の粒子とともに溶け合うような独自の質感が唯一無二で、国内アニメMV屈指の完成度。"
  },
  {
    id: "2026-05-22-jp-04",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "初星学園「Wildest Flower」 — Character Animation Film",
    creator: "大橋隆之 / CALF（学園アイドルマスター）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=iiiLtE4w2pE",
    creatorUrl: "https://www.behance.net/ohashitakashi",
    articleUrl: "https://www.stashmedia.tv/takashi-ohashi-calf-plant-the-wildest-flower-for-hatsuboshi-gakuen-in-new-music-video/",
    publishedDate: "2026-03-19",
    genre: ["アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/iiiLtE4w2pE/mqdefault.jpg",
    notes: "学園アイドルマスターの花海咲季（元アスリート転向アイドル）をフィーチャーした楽曲のキャラクターアニメーション映像。CALF所属の大橋隆之監督が担当しSTASHメディアに特集された鮮烈な色彩設計とダイナミックな作画が圧巻。ゲームキャラクターの覚醒をフルアニメーションで描き、日本のキャラクターアニメーション制作の現在地を示す傑作。"
  },
  {
    id: "2026-05-22-jp-05",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "劇場版チェンソーマン レゼ篇 — Official Trailer",
    creator: "MAPPA",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=tAzAhDNdehs",
    creatorUrl: "https://www.mappa.co.jp/",
    articleUrl: "https://www.crunchyroll.com/news/latest/2025/10/13/chainsaw-man-the-movie-reze-arc-unveils-explosive-new-trailer",
    publishedDate: "2025-07-04",
    genre: ["アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/tAzAhDNdehs/mqdefault.jpg",
    notes: "MAPPAが制作した劇場版チェンソーマン『レゼ篇』公式トレーラー（Anime Expo 2025解禁）。2025年9月19日日本公開・10月24日米国公開。爆弾娘レゼとデンジの激戦をMAPPA渾身のアクション作画で描き、劇場版アニメのトレーラーとして構成面でも完成度が高い。米津玄師主題歌との相乗効果もあり2025年の国産劇場版アニメを代表する一作。"
  },
  {
    id: "2026-05-22-global-01",
    date: "2026-05-22",
    type: "video",
    region: "global",
    title: "Trails Will Blaze — BBC Winter Olympics 2026",
    creator: "NOMINT / BBC Creative",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1158419326",
    creatorUrl: "https://vimeo.com/nomint",
    articleUrl: "https://stopmotionmagazine.com/bbc-trails-will-blaze-stop-motion-winter-olympics-2026/",
    publishedDate: "2026-02-13",
    genre: ["CM", "タイトル/OP"],
    techniques: ["ストップモーション", "実写合成"],
    thumbnail: "https://vumbnail.com/1158419326.jpg",
    notes: "ミラノ・コルティナ2026冬季五輪のBBCトレーラー。700体の3Dプリント選手フィギュアに実火を用いたストップモーション撮影で制作。イタリア・ドロミテの縮小模型を舞台にVerdiの「レクイエム」をBBC交響楽団がライブ録音。Motionographer採点8.62超えの2026年上半期最高傑作。"
  },
  {
    id: "2026-05-22-global-02",
    date: "2026-05-22",
    type: "video",
    region: "global",
    title: "BMW Heart of Joy — Meet Okto the Octopus",
    creator: "Untold Studios / Jung von Matt",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=t4tO5htFvpc",
    creatorUrl: "https://www.untoldstudios.com/",
    articleUrl: "https://www.stashmedia.tv/dancing-with-myself-okto-the-octopus-oscillates-for-bmw/",
    publishedDate: "2025-06-17",
    genre: ["CM", "3DCG"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/t4tO5htFvpc/mqdefault.jpg",
    notes: "タコの分散神経系＝BMW次世代中央制御ユニットというアナロジーから生まれたCMキャラクター「Okto」。南アフリカ実写水中映像へのフルCG合成のクオリティが圧巻。2026 VES Awards Outstanding Visual Effects / Compositing 受賞、Webbyアワードベストアニメーション・モーショングラフィクス受賞。"
  },
  {
    id: "2026-05-22-global-03",
    date: "2026-05-22",
    type: "video",
    region: "global",
    title: "Finch — Whatever It Takes to Get Through the Day",
    creator: "Kirsten Lepore / Mathematic",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Har-tUpSmmU",
    creatorUrl: "https://mathematic.tv/",
    articleUrl: "https://adage.com/creativity/creative-strategy-tactics/aa-finch-whatever-it-takes-to-get-through-the-day/",
    publishedDate: "2026-05-21",
    genre: ["CM", "アニメーション"],
    techniques: ["3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/Har-tUpSmmU/mqdefault.jpg",
    notes: "セルフケアアプリFinchのファーストブランドキャンペーン（5/21公開・昨日リリース）。Oscar ノミネート＆Emmy 受賞監督Kirsten Lepore（Mathematic）が手がけた90秒アニメミュージカル。ケーキをむさぼる・怒りの雑巾がけ・剣で枕を叩き割るなど『何とかやり過ごす日々』の滑稽さを愛らしく描く。"
  },
  {
    id: "2026-05-22-global-04",
    date: "2026-05-22",
    type: "video",
    region: "global",
    title: "Squarespace — Blueprint AI",
    creator: "ManvsMachine",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1068776467",
    creatorUrl: "https://mvsm.com/",
    articleUrl: "https://lbbonline.com/news/squarespace-introduces-its-ai-website-builder-with-a-human-touch",
    publishedDate: "2025-03-25",
    genre: ["CM", "ブランディング"],
    techniques: ["モーフィング", "実写合成"],
    thumbnail: "https://vumbnail.com/1068776467.jpg",
    notes: "Squarespace AIウェブビルダー「Blueprint AI」のローンチCM。デザイナーのスケッチブック上のアイデアが実際に飛び出し、デジタルUIへ変換される様子を実写＋モーショングラフィクスで表現。ManvsMachineらしいエレガントなトランジションと精緻な質感設計が際立つブランドフィルム。"
  },
  {
    id: "2026-05-22-global-05",
    date: "2026-05-22",
    type: "video",
    region: "global",
    title: "HAG — Official Trailer",
    creator: "Anna Ginsburg / Strange Beast / Passion Pictures",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1113936655",
    creatorUrl: "https://www.strangebeast.tv/",
    articleUrl: "https://lbbonline.com/news/Passion-Pictures-and-Strange-Beast-Win-at-SXSW-2026",
    publishedDate: "2025-11-15",
    genre: ["アニメーション", "実験的"],
    techniques: ["2Dアニメーション", "モーフィング"],
    thumbnail: "https://vumbnail.com/1113936655.jpg",
    notes: "SXSW 2026アニメーション部門Special Jury Award受賞の短編。別れ・生物時計・家父長制の圧力をダークコメディで描いたBFI出資作品。Anna Ginsburgの独自キャラクターデザインと大胆な色使い、メタモルフォーゼ的アニメーションが強烈な印象を残す。現在国際フェスティバル巡回中。"
  },
  // ===== 2026-05-21 =====
  {
    id: "2026-05-21-jp-01",
    date: "2026-05-21",
    region: "jp",
    title: "AFEELA Prototype 2026 | Concept Movie",
    creator: "WOW inc. / Sony Honda Mobility",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=tMkmiZS0brQ",
    creatorUrl: "https://www.w0w.co.jp/en/",
    articleUrl: "https://www.shm-afeela.com/en/news/2026-01-06/",
    publishedDate: "2026-01-06",
    genre: ["ブランディング", "3DCG"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/tMkmiZS0brQ/mqdefault.jpg",
    notes: "ソニー・ホンダモビリティのEV『AFEELA』がCES 2026でワールドプレミアした際の公式コンセプトムービー。東京のビジュアルデザインスタジオWOW inc.が手がけた3DCGと動的UIアニメーションの融合映像で、車体フォルムとデジタルインターフェースが有機的に絡み合う。モビリティの未来を高い審美眼で提示した意欲的なブランドフィルム。"
  },
  {
    id: "2026-05-21-jp-02",
    date: "2026-05-21",
    region: "jp",
    title: "MULTRA Brand Film",
    creator: "MULTRA Inc.",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1135619204",
    creatorUrl: "https://vimeo.com/multra",
    articleUrl: "https://www.stashmedia.tv/multra-studio-makes-stash-debut-with-new-brand-film/",
    publishedDate: "2025-10-01",
    genre: ["ブランディング", "モーショングラフィクス"],
    techniques: ["2Dアニメーション", "モーフィング"],
    thumbnail: "https://vumbnail.com/1135619204.jpg",
    notes: "東京のモーションデザインスタジオMULTRAによるSTASHデビュー自主制作ブランドフィルム。ジャズィーなリズムとともに多様なクリエイティブアイデアが連続・変容するマルチメディア表現。手描きキャラクターとグラフィックモーションがシームレスに融合し、スタジオのクリエイティブDNAを余すところなく体現する。"
  },
  {
    id: "2026-05-21-jp-03",
    date: "2026-05-21",
    region: "jp",
    title: "パワフルプロ野球2026-2027 オープニングムービー",
    creator: "KOO-KI x Konami Digital Entertainment",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=wOjrANePk1c",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://koo-ki.co.jp/works/detail/pawa-2026-2027",
    publishedDate: "2026-03-12",
    genre: ["タイトル/OP", "3DCG"],
    techniques: ["3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/wOjrANePk1c/mqdefault.jpg",
    notes: "野球ゲームシリーズ30周年を飾るオープニングムービー。福岡の映像集団KOO-KIが歴代WBC名場面をリイマジネーションし、イチロー・大谷翔平ら伝説的選手が集結するダイナミックな3DCGシーンを展開。スポーツゲームOPの域を超えた映像クオリティは国内外のゲームファン・映像ファンから高い評価を受ける。"
  },
  {
    id: "2026-05-21-jp-04",
    date: "2026-05-21",
    region: "jp",
    title: "HIDARI（ひだり） - ストップモーション侍映画 パイロット版",
    creator: "Whatever Co. / dwarf studios / TECARAT（川村真司監督）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=DpefYPLH67A",
    creatorUrl: "https://whatever.co/work/hidari/",
    articleUrl: "https://variety.com/2026/film/global/keanu-reeves-voice-lead-stop-motion-samurai-film-hidari-1236751402/",
    publishedDate: "2023-03-27",
    genre: ["アニメーション"],
    techniques: ["ストップモーション"],
    thumbnail: "https://img.youtube.com/vi/DpefYPLH67A/mqdefault.jpg",
    notes: "全キャラクターを木から手彫りしフレームごとに動かすストップモーション時代劇の短編パイロット版。4.9M再生を突破し2026年5月カンヌAnnecy Showcaseへ選出。同月キアヌ・リーブスのリード声優起用が発表され再び世界から注目を集めた、日本の手仕事アニメーションの金字塔。"
  },
  {
    id: "2026-05-21-jp-05",
    date: "2026-05-21",
    region: "jp",
    title: "Ado「ビバリウム」Official Music Video",
    creator: "林響太朗 / ACROBAT FILM",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=YvYii6dluM8",
    creatorUrl: "https://www.universal-music.co.jp/ado/",
    articleUrl: "https://natalie.mu/music/news/662104",
    publishedDate: "2026-02-28",
    genre: ["MV"],
    techniques: ["実写合成"],
    thumbnail: "https://img.youtube.com/vi/YvYii6dluM8/mqdefault.jpg",
    notes: "Ado初の完全実写MV。自身の半生をテーマにした楽曲に合わせ林響太朗監督が300カット超の迫力映像を構築した意欲作。水中撮影・逆光シルエット・ハイヒール疾走など多彩な手法を組み合わせ、Adoの感情の振れ幅を余すところなく映像化。日本音楽MVの新境地として各メディアが絶賛した2026年の注目作。"
  },
  {
    id: "2026-05-21-global-01",
    date: "2026-05-21",
    region: "global",
    title: "Coinbase — System Update",
    creator: "BUCK / Isle of Any",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=SemnKhDNZVU",
    creatorUrl: "https://buck.co/work/coinbase-system-update",
    articleUrl: "https://www.stashmedia.tv/buck-cracks-the-code-for-coinbase/",
    publishedDate: "2025-05-07",
    genre: ["CM", "ブランディング"],
    techniques: ["2Dアニメーション", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/SemnKhDNZVU/mqdefault.jpg",
    notes: "ASCIIアートと2Dアニメーションを融合させたCoinbaseのブランドアンセムフィルム。旧来の銀行システムの『ブルースクリーン・オブ・デス』から始まりCoinbase主導の新世界への再起動を描く。Houdini・C4D・Cavalry・After Effectsを駆使した技術的にも先鋭的な映像はNBAプレーオフ初放映で400万超視聴、D&ADアワードも受賞。"
  },
  {
    id: "2026-05-21-global-02",
    date: "2026-05-21",
    region: "global",
    title: "Affinity — Creative Freedom",
    creator: "ManvsMachine / Canva",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=CzPzRxDoirM",
    creatorUrl: "https://mvsm.com/project/canva-affinity",
    articleUrl: "https://www.stashmedia.tv/zero-bucks-given-manvsmachine-keeps-it-kinetic-for-canva/",
    publishedDate: "2025-11-07",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "2Dアニメーション", "キネティックタイポ"],
    thumbnail: "https://img.youtube.com/vi/CzPzRxDoirM/mqdefault.jpg",
    notes: "Canvaが完全無料化したデザインツール『Affinity』ローンチを飾るブランドキャンペーン映像。ManvsMachineが3D・2Dモーション・キネティックタイポグラフィ・手描きイラストを縦横無尽に融合させ、クリエイターへの解放宣言を表現したパワフルなハイプフィルム。1週間で100万人登録突破を達成した歴史的プロダクトローンチの象徴的映像。"
  },
  {
    id: "2026-05-21-global-03",
    date: "2026-05-21",
    region: "global",
    title: "NBC Primetime in Milan — Winter Olympics 2026 Title Sequence",
    creator: "Imaginary Forces",
    platform: "Vimeo",
    videoUrl: "https://imaginaryforces.com/project/winter-olympic-games-milan-cortina-2026",
    creatorUrl: "https://imaginaryforces.com/",
    articleUrl: "https://www.nbcsports.com/pressbox/press-releases/nbc-sports-selected-imaginary-forces-to-create-cinematic-main-title-sequence-for-primetime-in-milan",
    publishedDate: "2026-02-06",
    genre: ["タイトル/OP"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "",
    notes: "ミラノ・コルティナ2026冬季五輪のNBC『Primetime in Milan』用メインタイトルシーケンス。ILM StageCraftのボリュメトリックスクリーンを用いた実写撮影と3DCGを融合させ、イタリアの冬景色の中でチームUSAの歴代名場面を描く。Imaginary Forcesが五輪タイトルの信頼を再び示した、ブロードキャストデザインの到達点。"
  },
  {
    id: "2026-05-21-global-04",
    date: "2026-05-21",
    region: "global",
    title: "Telstra — Outback to Orbit | Satellite Messaging Campaign",
    creator: "Passion Animation / Bear Meets Eagle On Fire",
    platform: "Vimeo",
    videoUrl: "https://www.creativereview.co.uk/telstra-satellite-messaging-stop-motion-campaign/",
    creatorUrl: "https://www.passion-animation.com/director/catherine-prowse/",
    articleUrl: "https://www.stashmedia.tv/heres-how-catherine-prowse-passion-animation-built-stop-motion-messaging-for-telstra/",
    publishedDate: "2026-04-15",
    genre: ["CM"],
    techniques: ["ストップモーション"],
    thumbnail: "",
    notes: "オーストラリアの通信会社Telstraのサテライトメッセージ機能を訴求した3部作ストップモーションCM。農場・砂漠・山岳のセットが物理的に回転しながら宇宙への接続を描く独創的なメカニズムが秀逸。Catherine Prowse（Passion Animation）が緻密な模型制作と撮影で実現した、2026年の傑作ストップモーションCMとして各メディアが絶賛。"
  },
  {
    id: "2026-05-21-global-05",
    date: "2026-05-21",
    region: "global",
    title: "OFFF Barcelona 2026 — Official Aftermovie",
    creator: "OFFF Festival",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1189630992",
    creatorUrl: "https://www.offf.barcelona/",
    articleUrl: "https://motionographer.com/news/offf-2026-returns-for-26th-year-in-celebration-of-creativity-art-and-design/",
    publishedDate: "2026-04-30",
    genre: ["モーショングラフィクス", "タイトル/OP"],
    techniques: ["タイポグラフィ", "実写合成"],
    thumbnail: "https://vumbnail.com/1189630992.jpg",
    notes: "デザイン・アニメーション・映像の世界的祭典OFFF Barcelona 2026（第26回）のオフィシャルアフタームービー。76カ国・5,500名/日が集結した会期の全容を収録し、Laundry Studiosによるメインタイトルや多数のスピーカー登壇映像も収められる。モーションデザイン業界の最前線を一度に体感できる、フェスティバルの記念碑的アーカイブ映像。"
  },
];
