/* ========================================
   Daily Motion Graphics Picks — Data
   ----------------------------------------
   このファイルは毎朝10時のスケジュールタスクが自動更新します。
   手動でも編集可能（フォーマットを保つこと）。

   各エントリのスキーマ:
   {
     id: "YYYY-MM-DD-jp-01",       // ユニークID
     date: "YYYY-MM-DD",           // ピックアップ日
     region: "jp" | "global",       // 国内 / 海外
     title: "作品タイトル",
     creator: "制作者・スタジオ名",
     platform: "YouTube",          // YouTube / Vimeo / X / TikTok / Behance 等
     videoUrl: "https://...",      // 動画本体URL
     creatorUrl: "https://...",    // 制作者ページURL（任意）
     articleUrl: "",               // 関連記事URL（任意）
     publishedDate: "YYYY-MM-DD",  // 作品の公開日
     genre: ["MV", "モーショングラフィクス"],
     techniques: ["3DCG", "タイポグラフィ"],
     thumbnail: "https://...",     // サムネイルURL（YouTube: https://img.youtube.com/vi/{ID}/mqdefault.jpg）
     notes: "注目ポイント（2-3行）"
   }
   ======================================== */

window.picksData = [
  // ===== 2026-06-06 MOTION JP =====
  {
    id: "2026-06-06-01",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "ドリエル「SLEEP FIGHTER Ⅱ」告知映像",
    creator: "ong_（Direction / Design / Motion Design）/ エスエス製薬 ドリエル",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=qHIDppwlX-c",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2025-06-30",
    genre: ["CM", "モーショングラフィクス"],
    techniques: ["キネティックタイポ", "2Dアニメーション", "タイポグラフィ", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/qHIDppwlX-c/mqdefault.jpg",
    notes: "エスエス製薬の睡眠補助薬「ドリエル」が協賛した睡眠計量e-SPORTS大会「SLEEP FIGHTER Ⅱ」の告知映像。ong_がDirection・Design・Motion Designを担当し、短尺SNS向けに情報とビジュアルを高密度に圧縮したキネティックタイポグラフィ設計が光る。ゲームのエネルギーと睡眠という逆説的テーマをポップなモーショングラフィクスで体現した、ong_流ブランドコミュニケーションの好例。"
  },
  {
    id: "2026-06-06-02",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "機動戦士Gundam GQuuuuuuX TVシリーズトレーラー",
    creator: "スタジオカラー × サンライズ（鶴巻和哉 監督）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=VZaqtgVtL1M",
    creatorUrl: "https://www.khara.co.jp/",
    articleUrl: "",
    publishedDate: "2024-12-04",
    genre: ["CM", "3DCG", "アニメーション"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/VZaqtgVtL1M/mqdefault.jpg",
    notes: "エヴァンゲリオンのスタジオカラーとガンダムのサンライズが初コラボした話題作「機動戦士Gundam GQuuuuuuX」（ジークアクス）のTVシリーズトレーラー。鶴巻和哉監督のもと2026年4月よりAmazonプライムビデオで見放題配信。カラー独自の繊細な光と影の設計がガンダムの機動美と融合し、宇宙コロニーに生きる少女が違法MSバトルに巻き込まれるドラマを凝縮した映像作りが秀逸。劇場版「GQuuuuuuX -Beginning-」は2025年1月17日にIMAX含む全国公開を果たした。"
  },
  {
    id: "2026-06-06-03",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "テイルズ オブ グレイセス エフ リマスタード ローンチトレーラー",
    creator: "バンダイナムコエンターテインメント / テイルズスタジオ",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=-KTKhYikM1M",
    creatorUrl: "https://www.bandainamcoent.co.jp/",
    articleUrl: "",
    publishedDate: "2025-01-16",
    genre: ["CM", "3DCG"],
    techniques: ["NPR", "セルシェード", "3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/-KTKhYikM1M/mqdefault.jpg",
    notes: "バンダイナムコのJRPGシリーズ「テイルズ オブ」伝統のセルシェードNPR 3DCGが最新ハードウェアで再解釈されたリマスタード作のローンチトレーラー。手描きアニメに近い繊細な陰影・色設計はシリーズ屈指の評価を受けており、BoAが歌うテーマ曲とともに2025年1月16日コンソール・PC・Nintendo Switch向けに発売された。アニメ調3DCGのセルシェード表現が国内ゲームで到達した美学的水準を示す代表的な一作。"
  },
  {
    id: "2026-06-06-04",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "アニメ「怪獣8号」第2期 ノンクレジットOP「You Can't Run From Yourself」AURORA",
    creator: "WOW inc.（CG制作）/ 吉崎響（ディレクター・スタジオカラー所属）/ 東映アニメーション",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=rH8FCwzOdpI",
    creatorUrl: "https://www.w0w.co.jp/",
    articleUrl: "https://www.w0w.co.jp/en/works/KaijuNo8_2nd",
    publishedDate: "2025-07-19",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/rH8FCwzOdpI/mqdefault.jpg",
    notes: "TVアニメ「怪獣8号」第2期（2025年7月19日放送開始）のノンクレジットOP映像。第1期に引き続きWOW inc.とスタジオカラー所属の吉崎響がタッグを組み制作し、人間と怪獣の狭間で揺れる日比野カフカの苦悩と決意を心象風景として昇華。ノルウェー出身のシンガーAURORAの楽曲の透明感と完璧に調和し、国内外のアニメファンから絶賛されたシーズン2の顔。WOW inc.がアニメOP映像制作でも国際水準のクリエイティブを発揮した好例。"
  },
  {
    id: "2026-06-06-05",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "TVアニメ「呪術廻戦」第3期「死滅回游 前編」ノンクレジットOP「AIZO / King Gnu」",
    creator: "MAPPA",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Xr032EhUDPw",
    creatorUrl: "https://www.mappa.co.jp/",
    articleUrl: "",
    publishedDate: "2026-01-08",
    genre: ["タイトル/OP", "モーショングラフィクス"],
    techniques: ["2Dアニメーション", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/Xr032EhUDPw/mqdefault.jpg",
    notes: "2026年1月8日放送開始の「呪術廻戦」第3期「死滅回游 前編」のノンクレジットOP。King Gnuの「AIZO」に乗せてMAPPAが渾身の疾走アクションシーケンスを展開し、虎杖悠仁の拳とサイゴ乙骨の剣が圧倒的スピード感でぶつかり合う。タイトルカードの漢字デザインと動的グラフィック処理が連続するタイポグラフィ演出も印象的で、MAPPAのアクション演出力と映像設計が最大値で発揮された一作。"
  },
  {
    id: "2026-06-06-06",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "「葬送のフリーレン」第2期 ノンクレジットOP「lulu. / Mrs. GREEN APPLE」",
    creator: "Madhouse（アニメーション制作）/ 齋藤圭一郎（監督）/ 北川敬一（OP絵コンテ・演出）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=C0BG3B7aksU",
    creatorUrl: "https://www.madhouse.co.jp/",
    articleUrl: "",
    publishedDate: "2026-01-16",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/C0BG3B7aksU/mqdefault.jpg",
    notes: "2026年1月16日放送開始の「葬送のフリーレン」第2期のノンクレジットOP映像。Mrs. GREEN APPLEのフェーズ3第1弾楽曲「lulu.」をOPテーマに採用し、生命と意志の継承というテーマを北川敬一の演出で映像化。穏やかながら広がりを感じさせる映像設計とシーズン2の核心に触れるビジュアルの連なりが深い余韻を残し、Madhouse制作の繊細な美術とともに2026年冬アニメを代表するOP映像として注目を集めた。"
  },
  {
    id: "2026-06-06-07",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "TVアニメ「ダンジョン飯」ノンクレジットOP「Sleep Walking Orchestra / BUMP OF CHICKEN」",
    creator: "TRIGGER（アニメーション制作）/ 今石洋之（監督）/ Netflix",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=60_2zt9l3Yk",
    creatorUrl: "https://www.trigger.co.jp/",
    articleUrl: "",
    publishedDate: "2024-01-05",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/60_2zt9l3Yk/mqdefault.jpg",
    notes: "九井諒子原作「ダンジョン飯」（2024年1月〜Netflix世界独占配信）のノンクレジットOP映像。TRIGGERが制作し今石洋之が監督を務め、BUMP OF CHICKENの「Sleep Walking Orchestra」の高揚感に乗せてライオス一行の冒険が躍動感あふれるアクションで展開。キャラクターの個性と魔物グルメというユニークなコンセプトを凝縮し、2024年のアニメOPの中で最高完成度のひとつとして国内外で絶賛を浴びた代表作。"
  },
  {
    id: "2026-06-06-08",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "「劇場版モノノ怪 第三章 蛇神」予告第一弾",
    creator: "ツインエンジン（制作）/ 中村健治（監督）/ 東宝",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=SXWGHjkWxXA",
    creatorUrl: "https://www.twin-engine.co.jp/",
    articleUrl: "",
    publishedDate: "2025-12-10",
    genre: ["アニメーション", "実験的"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/SXWGHjkWxXA/mqdefault.jpg",
    notes: "2026年5月29日公開の劇場版モノノ怪三部作完結篇の予告映像。浮世絵・歌舞伎の意匠とサイケデリックな色彩・文様が有機的に融合する中村健治独自の視覚言語が全開で展開し、薬売りと蛇神の最終対決を極彩色の映像美で予告。「唐傘篇」「眩い闇篇」と続く三部作のクライマックスに相応しい造形美と映像密度で、日本独自の伝統アート×アニメーション表現の究極形を示す完結篇。"
  },
  {
    id: "2026-06-06-09",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "Number_i「Numbers Ur Zone」Official Music Video",
    creator: "P.I.C.S. management（鴨下大輝 Director）/ Number_i（平野紫耀・神宮寺勇太・岸優太）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=-FGFbUfosl8",
    creatorUrl: "https://www.pics.tokyo/",
    articleUrl: "https://www.pics.tokyo/works/number_i_numbers-ur-zone/",
    publishedDate: "2025-09-15",
    genre: ["MV"],
    techniques: ["実写合成", "タイポグラフィ", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/-FGFbUfosl8/mqdefault.jpg",
    notes: "Number_iの2025年9月15日リリースデジタルシングルのOfficial MV。P.I.C.S. managementの鴨下大輝がDirectorを担当し、平野紫耀・神宮寺勇太・岸優太の3人がダイナミックな振り付けを披露。スタイリッシュなビジュアル設計とモーショングラフィクスを融合させアイドルMVの定型を超えた洗練された映像表現を実現。P.I.C.S.がNumber_iのMV制作で継続的に確立してきた高品質な映像クリエイティブの到達点として注目を集める。"
  },
  {
    id: "2026-06-06-10",
    date: "2026-06-06",
    type: "video",
    region: "jp",
    title: "映画「デッドデッドデーモンズデデデデデストラクション」本予告",
    creator: "Science SARU（アニメーション制作）/ 黒川智之（監督）/ GAGA",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=JqsPrYf5ZYM",
    creatorUrl: "https://science-saru.com/",
    articleUrl: "https://dededede.jp/",
    publishedDate: "2024-02-22",
    genre: ["アニメーション", "実験的"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/JqsPrYf5ZYM/mqdefault.jpg",
    notes: "浅野いにお原作SF漫画を初映像化した劇場版「デッドデッドデーモンズデデデデデストラクション」（前章2024年3月22日・後章5月24日公開）の本予告映像。Science SARUの黒川智之監督が手がけ、東京上空に巨大UFOが8年間浮かぶ非日常世界での女子高生の友情と青春を独特のタッチで描く。主演声優の幾田りら・あのが楽曲を担当した主題歌とともに独自の世界観と映像美で2024年国内アニメ映画の最重要作となり、Science SARUの表現の幅広さを示した。"
  },
  // ===== 2026-06-05 MOTION JP =====
  {
    id: "2026-06-05-01",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "GUILTY GEAR STRIVE: DUAL RULERS ノンクレジットOP「AXCLUSION」",
    creator: "Arc System Works / SANZIGEN（森川成 監督）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=-5w45MRwr08",
    creatorUrl: "https://www.sanzigen.co.jp/",
    articleUrl: "https://www.arcsystemworks.com/anime-adaptation-guilty-gear-strive-dual-rulers-announced/",
    publishedDate: "2025-03-16",
    genre: ["3DCG", "タイトル/OP"],
    techniques: ["NPR", "セルシェード", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/-5w45MRwr08/mqdefault.jpg",
    notes: "格闘ゲーム「GUILTY GEAR -STRIVE-」を原作にSANZIGENが制作したTVアニメ「GUILTY GEAR STRIVE: DUAL RULERS」（2025年4月〜5月放送）のノンクレジットOP映像。「BanG Dream!」シリーズで磨き上げたNPRセルシェード3DCG技術がバトルアクションでも全開で展開。主題歌「AXCLUSION」（ulma sound junction）のハードロックエネルギーとシン・カイスケの3DCGアクションが完璧に融合し、SANZIGENのNPR進化形として国内外のアニメファン・CGクリエイターから高い評価を集めた。"
  },
  {
    id: "2026-06-05-02",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "BanG Dream! YUME∞MITA 公式Trailer 1",
    creator: "SANZIGEN / Bushiroad / 梅津朋実（監督）/ Nichicaline",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=7fdSXo-be7o",
    creatorUrl: "https://www.sanzigen.co.jp/",
    articleUrl: "https://anime.bang-dream.com/yumemita/",
    publishedDate: "2026-04-01",
    genre: ["3DCG", "アニメーション", "CM"],
    techniques: ["NPR", "セルシェード", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/7fdSXo-be7o/mqdefault.jpg",
    notes: "2026年7月2日より放送開始のTVアニメ「BanG Dream! YUME∞MITA（ゆめ∞みた）」第1弾トレーラー。仮想と現実を超えた運命の共鳴バンド「夢限大みゅーたいぷ」を主役にSANZIGENが制作。「BanG Dream! Ave Mujica」「ニワトリ・ファイター」と続くSANZIGENのNPRセルシェード最新進化形として注目を集める2026年夏アニメ。梅津朋実監督のもと、バーチャルとリアルが交差する世界観を全力の3DCGで体現する。"
  },
  {
    id: "2026-06-05-03",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "乃木坂46「不道徳な夏」MUSIC VIDEO",
    creator: "王一川（maxilla）Director / 乃木坂46 / Sony Music Odessa",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=6nLBdqoczxE",
    creatorUrl: "https://maxilla.jp/",
    articleUrl: "https://barks.jp/news/1002250/",
    publishedDate: "2025-07-30",
    genre: ["MV"],
    techniques: ["実写合成"],
    thumbnail: "https://img.youtube.com/vi/6nLBdqoczxE/mqdefault.jpg",
    notes: "39thシングル「Same numbers」収録のアンダー楽曲MVで、4期生・金川紗耶がセンターを務める。maxillaの王一川がDirectorを担当し、静岡・エコパスタジアムを舞台にアンダーメンバーが陽気に踊り歌う鮮やかな夏映像を完成。maxillaが近年継続的にノギザカMVに携わり、洗練されたポップなビジュアル設計でアイドル映像に新鮮な視点を持ち込んできた実績の一端を示す2025年夏の傑作。"
  },
  {
    id: "2026-06-05-04",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "ChroNoiR「春の予感」MV",
    creator: "ChroNoiR（葛葉・叶）/ ANYCOLOR / maxilla（Art Direction）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=G_nTDFrZIqQ",
    creatorUrl: "https://maxilla.jp/",
    articleUrl: "",
    publishedDate: "2025-03-31",
    genre: ["MV", "アニメーション"],
    techniques: ["2Dアニメーション", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/G_nTDFrZIqQ/mqdefault.jpg",
    notes: "にじさんじを代表するVTuberデュオ「ChroNoiR」（葛葉＆叶）の楽曲「春の予感」MV。maxillaはChroNoiRの「Catch Fire」MVでDirection/Produceを担当してきた実績を持ち、日本のVTuberカルチャーと本格映像制作の融合を象徴する。淡い春の情景の中、ふたりの関係性を繊細なアニメーション×モーションデザインで映像化した一作。VTuber映像クリエイティブの質的向上を示す2025年春の好例。"
  },
  {
    id: "2026-06-05-05",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "YOASOBI「Watch me!」Official Music Video（ウィッチウォッチOP）",
    creator: "Folium / 中外勇（Director）/ MULTRA（山下大誠 Design・松岡有機 Motion Design）/ Sony Music",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=evtoG-4dLM4",
    creatorUrl: "https://vimeo.com/multra",
    articleUrl: "https://anitrendz.net/news/2025/05/18/yoasobi-releases-music-video-for-witch-watch-op-watch-me/",
    publishedDate: "2025-05-18",
    genre: ["タイトル/OP", "モーショングラフィクス"],
    techniques: ["2Dアニメーション", "モーショングラフィクス", "キネティックタイポ"],
    thumbnail: "https://img.youtube.com/vi/evtoG-4dLM4/mqdefault.jpg",
    notes: "TVアニメ「ウィッチウォッチ」（2025年春）第1OPテーマのOfficial Music Video。FoliumのYu NakagaitoがDirectionを担当し、MULTRAの山下大誠（Design）と松岡有機（Motion Design）がグラフィックス・モーションを制作。STASH掲載スタジオMULTRAの現代的センスが随所に光り、YOASOBIの爽快なメロディに合わせて魔女少女の感情をキネティックタイポグラフィ×アニメーションで体現。東京発モーションデザインスタジオMULTRAの実力が広くに示された一作。"
  },
  {
    id: "2026-06-05-06",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "ONE PIECE 112巻発売記念PV「巨大な冒険、はじまる。」",
    creator: "東映アニメーション / 集英社 / maxilla（Art Direction）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=H8FHoOlzh1Y",
    creatorUrl: "https://maxilla.jp/",
    articleUrl: "https://one-piece.com/news/73342/index.html",
    publishedDate: "2025-07-04",
    genre: ["CM", "ブランディング"],
    techniques: ["2Dアニメーション", "セルアニメ"],
    thumbnail: "https://img.youtube.com/vi/H8FHoOlzh1Y/mqdefault.jpg",
    notes: "週刊少年ジャンプ連載「ONE PIECE」112巻（2025年7月4日発売）の発売記念PV。「来たぞ、エルバフ。」のキャッチコピーのもと、エルバフ編開幕を告げる高品質な東映アニメーション映像を短編に凝縮。maxillaがONE PIECEプロジェクトのArt Directionを担当してきた実績とも連動し、映像・グラフィック・イベントを横断するビジュアルキャンペーン全体の設計として大きな注目を集めた。"
  },
  {
    id: "2026-06-05-07",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "第76回NHK紅白歌合戦 矢沢永吉「止まらないHa~Ha」ステージ映像（KOO-KI制作）",
    creator: "KOO-KI（空気株式会社）/ NHK",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=ZXgJFIHsdo8",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://koo-ki.co.jp/works/detail/nhk-kouhaku-eikichiyazawa",
    publishedDate: "2025-12-31",
    genre: ["ブランディング", "モーショングラフィクス"],
    techniques: ["3DCG", "モーショングラフィクス", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/ZXgJFIHsdo8/mqdefault.jpg",
    notes: "第76回NHK紅白歌合戦（2025年12月31日）でソロ50周年を飾った矢沢永吉のステージで使用されたバックビジョン映像をKOO-KIが制作。サプライズ登場×圧巻のパフォーマンスと融合するKOO-KI設計のモーショングラフィクス×LEDステージビジョンが、日本最大の生放送を彩った。スポーツ・ゲーム・テレビ放送にわたるKOO-KIのブロードキャスト映像演出力が最高舞台で発揮されたケーススタディ。"
  },
  {
    id: "2026-06-05-08",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "大阪・関西万博 開会式 オープニングムービー「生命のリレー」（平牧和彦/TYO）",
    creator: "平牧和彦（TYO）Direction・Edit・Composite / 長谷川白紙 Music",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=8X_bgcgpORQ",
    creatorUrl: "https://eizo100.jp/video/105124",
    articleUrl: "https://x.com/jamespond628/status/1910966436870447126",
    publishedDate: "2025-04-12",
    genre: ["モーショングラフィクス", "実験的"],
    techniques: ["2Dアニメーション", "3DCG", "AI生成", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/8X_bgcgpORQ/mqdefault.jpg",
    notes: "2025年4月12日に開幕した大阪・関西万博（Expo 2025）の開会式で冒頭上映されたオープニングムービー。テーマ「生命のリレー」のもとTYOの平牧和彦がディレクション・編集・コンポジットを担当し、長谷川白紙の音楽とともに実写・アニメ・CG・ボリュメトリックスキャンを「コラージュ的」に融合した2分4秒の大作。万博の環状スクリーンと中央山型スクリーンという特殊な空間に最適化された映像設計が映像作家100人2026に選出された。"
  },
  {
    id: "2026-06-05-09",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "TVアニメ「異修羅」第2期 メインPV",
    creator: "Passione / SANZIGEN（CGアニメーション制作）/ Disney+",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=HwS08hlvhgw",
    creatorUrl: "https://www.sanzigen.co.jp/",
    articleUrl: "https://www.lisani.jp/0000272738/",
    publishedDate: "2024-12-23",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/HwS08hlvhgw/mqdefault.jpg",
    notes: "ファンタジーバトルアニメ「異修羅」第2期（2025年1月放送・Disney+配信）のメインPV。アニメーション制作はPassione、SANJIGENがCGアニメーション制作・撮影を担当した協業体制で、異なる修羅たちが究極の強さを争う世界観を濃密な映像で体現。第1期から引き継ぐ骨太なファンタジーアクションのビジュアル設計を踏まえながら、第2期での進化を示す解禁映像として国内アニメファンの期待を高めた。"
  },
  {
    id: "2026-06-05-10",
    date: "2026-06-05",
    type: "video",
    region: "jp",
    title: "RECRUIT じゃらん「スペシャルWEEK 2025年4月」CM",
    creator: "株式会社リクルート / じゃらんnet",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=jRu62MLbSrE",
    creatorUrl: "https://www.jalan.net/",
    articleUrl: "",
    publishedDate: "2025-04-01",
    genre: ["CM"],
    techniques: ["キネティックタイポ", "2Dアニメーション", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/jRu62MLbSrE/mqdefault.jpg",
    notes: "旅行予約サービス「じゃらんnet」の「スペシャルWEEK 2025年4月」篇15秒CMシリーズ。リズミカルなキネティックタイポグラフィと鮮やかな2Dアニメーションで旅のワクワク感を凝縮した短尺CM。ong_がじゃらんの「お得な10日間」CMシリーズのモーションデザインを担当してきた流れの中、スピーディーで楽しいビジュアル言語でユーザーの旅行意欲を刺激する日本のWebCM設計の好例。"
  },
  // ===== 2026-06-04 MOTION JP =====
  {
    id: "2026-06-04-01",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "北斗の拳 -FIST OF THE NORTH STAR- PV第2弾",
    creator: "ライデンフィルム / TMS Entertainment / Warner Bros. Japan",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Gux_dYHDMK4",
    creatorUrl: "https://hokuto-anime.com/",
    articleUrl: "",
    publishedDate: "2026-03-12",
    genre: ["3DCG", "CM"],
    techniques: ["NPR", "セルシェード", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/Gux_dYHDMK4/mqdefault.jpg",
    notes: "Amazon Prime Video独占配信の3DCGリメイク「北斗の拳 -FIST OF THE NORTH STAR-」（2026年4月10日配信開始）の第2弾PV。ライデンフィルム×TMS Entertainment制作で、CGディレクター池田晋治が率いるチームが北斗百裂拳をフル3DCGで再現。セルルック表現とアクション作画の融合がどこまで到達できるかに国内外から注目が集まり、3DCGアニメの現在地を測る試金石として映像界に問題提起した。"
  },
  {
    id: "2026-06-04-02",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "大河ドラマ「べらぼう」メインテーマ(オープニング)ノンクレジットタイトルバック",
    creator: "LIKI inc.（デザイン・モーション・作画アニメーション）/ NHK",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=CQkMDSWltOI",
    creatorUrl: "https://www.likiinc.com/",
    articleUrl: "",
    publishedDate: "2025-01-10",
    genre: ["タイトル/OP"],
    techniques: ["2Dアニメーション", "モーショングラフィクス", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/CQkMDSWltOI/mqdefault.jpg",
    notes: "2025年NHK大河ドラマ「べらぼう〜蔦重栄華乃夢噺〜」のオープニング映像をLIKI inc.がデザイン・モーション・作画アニメーションで担当。江戸期の浮世絵・歌麿・北斎・百鬼夜行などを昇華したコラージュ映像に動く作字が絡み合い、江戸文化の熱量をダイナミックなモーションで体現。「モーショングラフィックスはビジュアルが重要」と語るLIKI inc.のフィロソフィーが大河ドラマという最大舞台で結実した一作。"
  },
  {
    id: "2026-06-04-03",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "ぜったくん「アスパラ feat. 木暮栄一 (the band apart)」Official Lyric Video",
    creator: "ong_（Direction / Motion Design）/ ぜったくん（楽曲）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LWxPe8Zy620",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2025-03-28",
    genre: ["リリックモーション", "モーショングラフィクス"],
    techniques: ["キネティックタイポ", "2Dアニメーション", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/LWxPe8Zy620/mqdefault.jpg",
    notes: "巣ごもり系マイルドラッパー・ぜったくんとthe band apart木暮栄一のコラボ曲「アスパラ」のリリックビデオ。ong_がDirection / Motion Designを担当し、春の街を歩くアスパラくんキャラクターを主役にキャッチーなキネティックタイポグラフィを展開。文字・イラスト・リズムが一体化した明るくポップな映像設計はong_の日本語リリックモーション設計の真骨頂で、ユニバーサルミュージック公式リリース。"
  },
  {
    id: "2026-06-04-04",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "アニメ『Dr.STONE SCIENCE FUTURE』最終シーズン第2クールノンクレジットOP映像「SUPERNOVA」KANA-BOON",
    creator: "渡部康成（P.I.C.S. management）/ Toho",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=HNYp4T0kMNU",
    creatorUrl: "https://www.pics.tokyo/",
    articleUrl: "https://www.pics.tokyo/works/drstone_opening/",
    publishedDate: "2025-07-10",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション", "3DCG", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/HNYp4T0kMNU/mqdefault.jpg",
    notes: "TVアニメ「Dr.STONE SCIENCE FUTURE」最終シーズン第2クール（2025年7月放送）OPをP.I.C.S.の渡部康成がディレクション。KANA-BOON「SUPERNOVA」の爆発的なエネルギーと千空たちの科学革命を疾走感あふれるカット割りで体現。同シーズンのEDも稲葉秀樹（P.I.C.S.）が担当するという両面体制で、日本アニメ映像制作の最前線を担ったP.I.C.S.の実力が光る。"
  },
  {
    id: "2026-06-04-05",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "HUGEN「PAPPIDOO（パッピドゥ）」Music Video",
    creator: "高橋李空/DOKUZEN（Director / Animation）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=jRxF8tqQg8Y",
    creatorUrl: "https://www.youtube.com/@HUGEN_official",
    articleUrl: "https://spincoaster.com/news/hugen-pappidoo-mv",
    publishedDate: "2026-02-27",
    genre: ["MV", "アニメーション"],
    techniques: ["ストップモーション", "2Dアニメーション", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/jRxF8tqQg8Y/mqdefault.jpg",
    notes: "名古屋発バンドHUGENの「パッピドゥ」MV。高橋李空/DOKUZENがDirectionとAnimationを担当し、アナログのカットアウトアニメーションとBlenderでの3DCGを融合した独自映像文法を確立。草・虫・雲・月石まで音楽に合わせて生き生きと踊る幻想的な世界観が人気を博し、映像作家100人2026に選出。手仕事のぬくもりとデジタルCGの精緻さが交差する映像美が秀逸。"
  },
  {
    id: "2026-06-04-06",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "七次元生徒会！「即物的アンサンブル」Official Music Video",
    creator: "クーテン（qootain）/ 南條沙歩（監督・アニメーション）/ OSTER project（楽曲）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=dHywSNVzdfQ",
    creatorUrl: "https://www.youtube.com/channel/UCHRCp0CSacVnTVS2Z4x9xYg",
    articleUrl: "",
    publishedDate: "2025-05-28",
    genre: ["MV", "アニメーション"],
    techniques: ["2Dアニメーション", "ストップモーション"],
    thumbnail: "https://img.youtube.com/vi/dHywSNVzdfQ/mqdefault.jpg",
    notes: "若手VTuberユニット・七次元生徒会の1st EP表題曲MV。クーテン（qootain）が制作を担当し、南條沙歩が監督・アニメーションを手がけたカットアウトアニメーション×デジタルアニメーションの混在表現が特徴。OSTER projectの楽曲と映像が巧みに絡み合い、キャラクターの個性をユーモラスかつ洗練された映像文法で描出。映像作家100人2026に記録され、VTuber×アニメーション映像の可能性を広げた。"
  },
  {
    id: "2026-06-04-07",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "阪神タイガース2026シーズン スタメン紹介前映像",
    creator: "KOO-KI（空気株式会社）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=8A0W_V5k1Ug",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "",
    publishedDate: "2026-04-10",
    genre: ["ブランディング", "CM"],
    techniques: ["3DCG", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/8A0W_V5k1Ug/mqdefault.jpg",
    notes: "甲子園球場でシーズン開幕を告げる2026年スタメン紹介前映像をKOO-KIが制作。阪神タイガースの情熱とスピード感を3DCGと動的グラフィックスで圧縮し、球場のビジョン向けに映える映像設計を実現。スポーツエンターテイメントの空間体験とモーショングラフィクスが融合したスタジアム映像の現代的事例として、スポーツブランディング映像の新基準を提示した。"
  },
  {
    id: "2026-06-04-08",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "TAKANAWA GATEWAY CITY 未来体験シアター「羊文学 - 未来地図2025」",
    creator: "WOW inc.（大保幸助 Creative Director / 曽根宏暢 Director）/ 羊文学（音楽）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=qh_JGRPpx0U",
    creatorUrl: "https://www.w0w.co.jp/",
    articleUrl: "https://www.w0w.co.jp/en/works/tgc",
    publishedDate: "2025-03-27",
    genre: ["ブランディング", "モーショングラフィクス"],
    techniques: ["3DCG", "モーショングラフィクス", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/qh_JGRPpx0U/mqdefault.jpg",
    notes: "2025年3月27日グランドオープンのTAKANAWA GATEWAY CITY内「THE LINK PILLAR 1」未来体験シアターにてWOW inc.が制作・上映中の没入型体験映像。大保幸助がCreative Directorを、曽根宏暢がDirectorを担当し、羊文学「未来地図2025」に乗せて都市・人・テクノロジーが共鳴する未来像を映像化。JR東日本の新しい都市開発と連動したモーションデザイン×体験型インスタレーションの最前線事例。"
  },
  {
    id: "2026-06-04-09",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "乃木坂46 六期生 | 櫻坂46 四期生 | 日向坂46 五期生「新参者 二〇二五 in TOKYU KABUKICHO TOWER」",
    creator: "ong_（Direction / Motion Design）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=9KHWZfy7AoU",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "https://tower.jp/article/news/2025/09/26/tg015",
    publishedDate: "2025-09-26",
    genre: ["CM", "ブランディング"],
    techniques: ["キネティックタイポ", "タイポグラフィ", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/9KHWZfy7AoU/mqdefault.jpg",
    notes: "乃木坂46六期生・櫻坂46四期生・日向坂46五期生が参加した坂道グループ合同企画「新参者 二〇二五 in TOKYU KABUKICHO TOWER」の公式合同告知映像。ong_がDirection・Design・Motion Designを担当し、3グループの個性を統一されたキネティックタイポグラフィで体現。2025年11月1〜30日の東急歌舞伎町タワーイベントのブランドコミュニケーションを映像で完結させた。"
  },
  {
    id: "2026-06-04-10",
    date: "2026-06-04",
    type: "video",
    region: "jp",
    title: "アニメ『Dr.STONE SCIENCE FUTURE』最終シーズン第2クールノンクレジットED映像「no man's world」音羽-otoha-",
    creator: "稲葉秀樹（P.I.C.S. management）/ 藤井大介（3DCG）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=slJjDE64mFY",
    creatorUrl: "https://www.pics.tokyo/",
    articleUrl: "https://www.pics.tokyo/works/drstone_ending/",
    publishedDate: "2025-07-10",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/slJjDE64mFY/mqdefault.jpg",
    notes: "TVアニメ「Dr.STONE SCIENCE FUTURE」最終シーズン第2クールエンディング映像。稲葉秀樹（P.I.C.S. management）がディレクション・アニメーション・撮影を担当し、3DCGを藤井大介が手がけた。音羽-otoha-「no man's world」の内省的な世界観に合わせ、孤独な科学少年の感情を2Dアニメーション×3DCG融合で映像化。同シーズンのOP（渡部康成監督）と対照的な静謐な演出で、P.I.C.S.の多彩な表現力を示す。"
  },
  // ===== 2026-06-03 MOTION JP =====
  {
    id: "2026-06-03-01",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "Vaundy「飛ぶ時」MV",
    creator: "Vaundy ART Work Studio / BONES Film（アニメーション）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=ARj1adoUoEU",
    creatorUrl: "https://vaundy.jp/",
    articleUrl: "",
    publishedDate: "2026-05-30",
    genre: ["MV"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/ARj1adoUoEU/mqdefault.jpg",
    notes: "TVアニメ「黄泉のツガイ」OPテーマ。荒川弘原作・BONES Film制作アニメの軽快なリズムが漲るOP映像として4月より先行放送された後、5月30日に公式MV初公開。安藤真裕監督の繊細な演出と楽曲が完璧に融合し、霊界と現代が交錯するユニークな世界観を疾走させる。VaundyがアニメのED「飛ぼうよ」（yamaへ楽曲提供）も手掛けた2026年春アニメを彩る核。"
  },
  {
    id: "2026-06-03-02",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "TVアニメ「マリッジトキシン」ノンクレジットOP｜平手友梨奈「Kill or Kiss」",
    creator: "SANZIGEN（サンジゲン） / 堀元宣（監督） / 永嶋大輝（CGディレクター）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=7xi16GVkCcA",
    creatorUrl: "https://www.sanzigen.co.jp/",
    articleUrl: "",
    publishedDate: "2026-04-14",
    genre: ["タイトル/OP", "3DCG"],
    techniques: ["NPR", "セルシェード", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/7xi16GVkCcA/mqdefault.jpg",
    notes: "ジャンプ+発「マリッジトキシン」（結婚詐欺師×殺し屋バディ）をSANZIGENがフル3DCGセルシェードで映像化。2026年4月フジテレビ「火曜アニメ！」枠放送。平手友梨奈「Kill or Kiss」を軸にSANZIGENの最新NPR技術を惜しみなく注ぎ込み、ポップかつアグレッシブなアクションシーンの質感が卓越している。BanG Dream! Ave Mujicaに続くSANZIGENのセルシェード進化形として国内外で注目された。"
  },
  {
    id: "2026-06-03-03",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "ヨルシカ「櫂」OFFICIAL VIDEO",
    creator: "加藤隆（アニメーション作家） / ヨルシカ（n-buna・suis）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=SIwfXPESJ8k",
    creatorUrl: "https://yorushika.com/",
    articleUrl: "https://realsound.jp/2026/03/post-2331031.html",
    publishedDate: "2026-03-11",
    genre: ["MV", "アニメーション"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/SIwfXPESJ8k/mqdefault.jpg",
    notes: "アルバム「二人称」（オリコン週間デジタルアルバム1位）の最終楽曲「櫂」のMV。「少年と先生の文通」を主題に、少年の描く一本の線からめくるめく幻想が広がる構成をアニメーション作家・加藤隆が担当。墨の筆触と空間表現が有機的に溶け合う独自の映像文法を展開し、n-bunaが「引用のない楽曲」と語る作品の根底に流れる静かな力を映像化した。"
  },
  {
    id: "2026-06-03-04",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "ong_ MOTION REEL 2025",
    creator: "ong_（モーショングラフィックデザイナー）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=7Em6X-w3TcI",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2025-05-14",
    genre: ["モーショングラフィクス"],
    techniques: ["キネティックタイポ", "タイポグラフィ", "モーショングラフィクス", "モーフィング"],
    thumbnail: "https://img.youtube.com/vi/7Em6X-w3TcI/mqdefault.jpg",
    notes: "キネティックタイポグラフィとモーショングラフィクスの第一人者ong_が2025年に発表したショーリール。JR東日本・三菱地所・サントリー・日テレNEWSなど多数の一流クライアントワークを凝縮し、文字が意味ではなくリズムとして宙を舞うong_独自の映像文法が全開。タイポグラフィ・アニメーション・モーフィングを有機的に繋いだ国内モーショングラフィクスの現在地を示す一作。"
  },
  {
    id: "2026-06-03-05",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "Pokémon Champions 4th Trailer",
    creator: "maxilla（Masaki Watanabe ディレクション） / The Pokémon Company",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=ZFZHyDdgMIo",
    creatorUrl: "https://maxilla.jp/",
    articleUrl: "",
    publishedDate: "2026-02-27",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "モーショングラフィクス", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/ZFZHyDdgMIo/mqdefault.jpg",
    notes: "ポケモン プレゼンツ 2026.2.27で解禁されたオンラインゲーム「Pokémon Champions」第4弾プロモーショントレーラー。maxillaのMasaki Watanabeがディレクションを担当し、2026年4月Nintendo Switch版リリースを前にグローバルブランドフィルムを設計。ポケモンIPのスケール感と対戦ゲームの熱量をモーショングラフィクスで体現し、世界規模タイトルのビジュアルコミュニケーション設計事例として注目を集めた。"
  },
  {
    id: "2026-06-03-06",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "INZONE | Designed to Win | Sony Official",
    creator: "maxilla（Yuya Yamaguchi ディレクション） / SIGNIF / BeansMagic Inc.",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=SPlB2YpLOMs",
    creatorUrl: "https://maxilla.jp/",
    articleUrl: "",
    publishedDate: "2025-04-01",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/SPlB2YpLOMs/mqdefault.jpg",
    notes: "ソニーのゲーミングギアブランド「INZONE」の「Designed to Win」グローバルブランドフィルム。maxillaのYuya Yamaguchiがディレクションを担当し、SIGNIFとBeansMagic Inc.がCGを制作。e-Sportsアスリートのメンタルとギアが融合する瞬間を精緻な3DCGモーションで体現した31秒の一作。maxillaが近年継続的に担当するゲーム・テック系グローバルブランドフィルムの好例として映像業界で参照されている。"
  },
  {
    id: "2026-06-03-07",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "ユミアのアトリエ〜追憶の錬金術士と幻創の地〜 キャラクタームービー（ユミア）",
    creator: "ガスト / コーエーテクモゲームス",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=0smi0hP7ZIU",
    creatorUrl: "https://www.gamecity.ne.jp/atelier/yumia/",
    articleUrl: "",
    publishedDate: "2025-02-27",
    genre: ["CM", "3DCG"],
    techniques: ["NPR", "セルシェード", "3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/0smi0hP7ZIU/mqdefault.jpg",
    notes: "コーエーテクモゲームス・ガストブランドJRPG「ユミアのアトリエ」（2025年3月21日発売）のキャラクタームービー。ガスト独自の柔らかいセルシェードNPR表現が手描きアニメに近い質感を実現し、女主人公ユミアのキャラクター性と錬金術の神秘的世界観を流麗な3DCGで表現。アトリエシリーズが積み上げてきたアニメ調3DCGの美学が凝縮され、JRPGビジュアル表現における国内セルシェードの高水準を示す。"
  },
  {
    id: "2026-06-03-08",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "TVアニメ「ダンダダン」オープニング映像｜Creepy Nuts「オトノケ」",
    creator: "Science SARU / Abel González Vidal（監督） / 加藤聡子（キャラクターデザイン）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Nw_XzGZ35As",
    creatorUrl: "https://science-saru.com/",
    articleUrl: "",
    publishedDate: "2024-10-03",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション", "キネティックタイポ", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/Nw_XzGZ35As/mqdefault.jpg",
    notes: "龍幸伸原作「ダンダダン」のアニメ化OP。Science SARUが手がける超高密度の作画とCreepy Nuts「オトノケ」の熱量が完璧にシンクロし、日本・海外双方のモーションデザインコミュニティから絶賛を浴びた。豪快なカット割り・大胆なタイポグラフィ処理・フォントの動的展開が一体となり、アニメOPにおけるキネティックタイポグラフィの新地平を示した2024年を代表するOP映像として現在も広く参照されている。"
  },
  {
    id: "2026-06-03-09",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "TVアニメ「あかね噺」本PV第1弾｜2026年4月放送開始",
    creator: "ゼクシズ / 渡辺歩（監督） / 永瀬アンナ（桜咲朱音 CV）/ アニプレックス",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=F72r44jo_fo",
    creatorUrl: "https://akane-banashi.com/",
    articleUrl: "https://www.aniplex.co.jp/lineup/akane-banashi/",
    publishedDate: "2025-12-19",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション", "セルアニメ"],
    thumbnail: "https://img.youtube.com/vi/F72r44jo_fo/mqdefault.jpg",
    notes: "「ジャンプ+」連載の落語漫画「あかね噺」がゼクシズ制作でTVアニメ化。父の汚名を晴らすべく落語の最高位を目指す桜咲朱音（CV:永瀬アンナ）の物語を本PVで初解禁。落語の所作・高座・着物の描写に宿る日本固有の視覚美と躍動感ある作画が印象的で、テレ朝系IMAnimation枠2026年4月放送・NetflixおよびABEMAで先行配信と国内外の注目を集めた一作。"
  },
  {
    id: "2026-06-03-10",
    date: "2026-06-03",
    type: "video",
    region: "jp",
    title: "Colors,Future!Summit 2024 TV CM",
    creator: "ong_（Direction / Design / Motion Design） / 川崎市市制100周年記念事業",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=frNXapv5_cY",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "https://colorsfuturesummit.jp/event/2024/",
    publishedDate: "2024-10-24",
    genre: ["CM", "モーショングラフィクス"],
    techniques: ["キネティックタイポ", "モーショングラフィクス", "モーフィング", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/frNXapv5_cY/mqdefault.jpg",
    notes: "川崎市市制100周年記念「Colors,Future!Summit 2024」（2024年11月2-3日）の公式プロモーション映像。「100」の数字が「川崎の川」を表す文字へとモーフィングしていくキネティックタイポグラフィが中核で、カラフルかつポップな色使いで100周年と川崎をブランド結合させたong_設計の傑作モーショングラフィクス。ロゴモーション×キネティックタイポのエッセンスが凝縮された地域ブランディング映像の模範例。"
  },
  // ===== 2026-06-02 MOTION JP =====
  {
    id: "2026-06-02-01",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "星街すいせい「Caramel Pain」MV",
    creator: "擬態するメタ（監督） / しまぐちニケ（キャラデザ・作画監督） / Bivi（編集・コンポジット）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=UpEPkPg8YP4",
    creatorUrl: "https://yasucra.com/",
    articleUrl: "https://yasucra.com/hoshimachi-caramelpain",
    publishedDate: "2025-03-27",
    genre: ["MV"],
    techniques: ["2Dアニメーション", "キネティックタイポ", "モーフィング"],
    thumbnail: "https://img.youtube.com/vi/UpEPkPg8YP4/mqdefault.jpg",
    notes: "VTuber・星街すいせいの楽曲MVを映像作家100人2025に選出された擬態するメタが監督。リリース直後に史上最速ミリオン達成。フローティングタイポグラフィで文字が意味ではなくリズムとして宙を舞い、連続変形するモーフィングで感情のグラデーションを映像化した鮮烈な一作。"
  },
  {
    id: "2026-06-02-02",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "R-1グランプリ2026 プロモーション映像フルバージョン",
    creator: "FUKUPOLY.INC（福田保孝 - CGディレクション・デザイン・アニメーション）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=-i_SiNojTDE",
    creatorUrl: "https://eizo100.jp/video/124015",
    articleUrl: "https://www.oricon.co.jp/news/2440870/full/",
    publishedDate: "2026-03-07",
    genre: ["CM", "モーショングラフィクス"],
    techniques: ["3DCG", "タイポグラフィ", "パーティクル"],
    thumbnail: "https://img.youtube.com/vi/-i_SiNojTDE/mqdefault.jpg",
    notes: "歴代R-1王者の3D顔を連打するカオスな世界観演出にCreepy Nuts「バレる!」が乗るハイテンションPV。FUKUPOLY.INCの福田保孝がCGディレクションを担当し、お笑いという一瞬の爆発力をモーショングラフィクスで体現した。笑いを映像設計で加速させる稀有なCGアプローチが光る2026年の傑作プロモーション。"
  },
  {
    id: "2026-06-02-03",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "ニワトリ・ファイター 公式PV第3弾",
    creator: "サンジゲン（SANZIGEN） / 小松英喬（監督） / 桜谷大（原作）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=EG5pLtPQztE",
    creatorUrl: "https://www.sanzigen.co.jp/",
    articleUrl: "",
    publishedDate: "2026-03-15",
    genre: ["3DCG", "タイトル/OP"],
    techniques: ["NPR", "セルシェード", "3DCG", "アニメーション"],
    thumbnail: "https://img.youtube.com/vi/EG5pLtPQztE/mqdefault.jpg",
    notes: "「1羽のニワトリが鬼獣から人類を守る」という奇想天外な設定をSANZIGENの全力NPR 3DCGで描く2026年春アニメ。公式PV累計1422万再生突破・Adult Swim Toonamiで放送され世界50以上の国と地域に配信中。BanG Dream!で磨き上げたセルシェード3DCGがコメディアクションにも完璧にマッチした、国内NPRアニメの現在形。"
  },
  {
    id: "2026-06-02-04",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "攻殻機動隊展 Ghost and the Shell Official Trailer",
    creator: "maxilla（アートディレクション） / Production I.G（映像コンテンツ）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=fao8K6XAI7w",
    creatorUrl: "https://maxilla.jp/",
    articleUrl: "https://www.tokyonode.jp/sp/exhibition-ghostintheshell/",
    publishedDate: "2026-01-22",
    genre: ["CM", "ブランディング"],
    techniques: ["モーショングラフィクス", "タイポグラフィ", "3DCG", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/fao8K6XAI7w/mqdefault.jpg",
    notes: "2026年1月30日〜4月5日に虎ノ門ヒルズ「TOKYO NODE」で開催されたシリーズ史上初の大規模展覧会のオフィシャルトレーラー。maxillaがアートディレクションを担当し30年に渡るGhost in the Shellアーカイブを凝縮した高密度映像設計が光る。Science SARUによる新アニメ情報も組み込まれ、展覧会ブランディング映像の一つの到達点として評価が高い。"
  },
  {
    id: "2026-06-02-05",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "劇場版「魔法使いの夜」最新映像｜2026年公開決定",
    creator: "ufotable",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=u05gaPDauh4",
    creatorUrl: "https://www.ufotable.com/",
    articleUrl: "https://mahoyo-movie.com/",
    publishedDate: "2026-02-21",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/u05gaPDauh4/mqdefault.jpg",
    notes: "TYPE-MOONの伝説的ビジュアルノベルをufotableが初の劇場アニメ化。2026年2月のufotableプロモーションリールで初解禁され、穏やかな日常と魔術が交錯する世界観をufotable独自の光と影の質感で描く。鬼滅の刃で世界が認めた同スタジオの次フェーズへの挑戦として国内外から高い期待が注がれる。"
  },
  {
    id: "2026-06-02-06",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "アニメ「スティール・ボール・ラン ジョジョの奇妙な冒険」PV第1弾",
    creator: "デイヴィッドプロダクション / 木村太郎（監督） / 高橋秀也（監督）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=EdarcSH9jmY",
    creatorUrl: "https://davidproduction.jp/",
    articleUrl: "https://jojo-portal.com/en/news/info/498/",
    publishedDate: "2025-12-19",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["2Dアニメーション", "セルアニメ"],
    thumbnail: "https://img.youtube.com/vi/EdarcSH9jmY/mqdefault.jpg",
    notes: "大西洋横断大陸横断レースを舞台にしたジョジョ第7部のアニメ化第1弾PV。デイヴィッドプロダクションが6作品連続でジョジョを手がける大一番で、Netflix世界同時配信という最大の舞台に臨む。2026年3月19日より1st STAGE（47分）先行配信開始、コバヤシヤスコによるシリーズ構成と塚根大介のキャラクターデザインが注目を集めた。"
  },
  {
    id: "2026-06-02-07",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "キタニタツヤ「カルチャー」MV",
    creator: "バーバパパ（監督） / キタニタツヤ",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=nWoDxPNHSlE",
    creatorUrl: "https://tatsuyakitani.com/",
    articleUrl: "https://skream.jp/news/2025/08/tatsuyakitani_culture.php",
    publishedDate: "2025-08-31",
    genre: ["MV"],
    techniques: ["2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/nWoDxPNHSlE/mqdefault.jpg",
    notes: "YouTube Music Weekend 10.0 supported by PlayStation（2025年8月29〜31日）でのサプライズリリース。音楽と映像を並行制作したことで生まれた有機的な一体感が特徴で、バーバパパが監督を担当。チェンソーマンOP「大脳的なランデブー」など話題作を手がけるキタニタツヤとのコラボで、2025年夏を代表するMVとして注目された。"
  },
  {
    id: "2026-06-02-08",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "MULTRA MOTION REEL",
    creator: "MULTRA",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/932758541",
    creatorUrl: "https://vimeo.com/multra",
    articleUrl: "https://eizo100.jp/archives/member/multra",
    publishedDate: "2024-06-01",
    genre: ["モーショングラフィクス", "実験的"],
    techniques: ["モーショングラフィクス", "2Dアニメーション", "モーフィング", "Vector"],
    thumbnail: "https://vumbnail.com/932758541.jpg",
    notes: "東京のモーションデザインスタジオMULTRAによるショーリール。多彩なクライアントワークとオリジナル表現の精選カットがジャズィなリズムとともに連続変容し、スタジオのクリエイティブDNAを一覧できる圧縮映像。映像作家100人2025に選出・STASHデビューを飾ったMULTRAの多彩な映像語彙が凝縮された一作。"
  },
  {
    id: "2026-06-02-09",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "BanG Dream! Ave Mujica - The Die is Cast - Official Trailer",
    creator: "サンジゲン（SANZIGEN）/ ブシロード",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Souwq8yepWQ",
    creatorUrl: "https://www.sanzigen.co.jp/",
    articleUrl: "https://en.bang-dream.com/anime/avemujica/",
    publishedDate: "2025-01-03",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["NPR", "セルシェード", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/Souwq8yepWQ/mqdefault.jpg",
    notes: "2025年1月より放送・SANZIGENが制作したフル3DCGアニメ「BanG Dream! Ave Mujica」の公式トレーラー。BanG Dream! It's MyGO!!!!!の続編として制作され、SANZIGENが長年かけて磨き上げたNPRセルシェード技術の集大成として国内外で高く評価。闇と耽美の世界観をリアルタイム3DCGで表現し、2Dアニメとの境界を消し去るほどの映像品質を誇る。"
  },
  {
    id: "2026-06-02-10",
    date: "2026-06-02",
    type: "video",
    region: "jp",
    title: "おジャ魔女どれみにょん「いっしょにあそぼ！」",
    creator: "KOO-KI（空気株式会社） / 白川東一（監督） / 芋虫（キャラクターデザイン）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=FBxrXivqZIM",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://www.doremi-anniv.com/news/2026032803.html",
    publishedDate: "2026-03-28",
    genre: ["アニメーション", "短編アニメ"],
    techniques: ["2Dアニメーション", "セルアニメ"],
    thumbnail: "https://img.youtube.com/vi/FBxrXivqZIM/mqdefault.jpg",
    notes: "おジャ魔女どれみ25周年を記念してKOO-KIが制作した新ショートアニメシリーズ。「ドッカ～ン！」終了後のその後を描き、ハナちゃんの涙で甦るちいさなどれみたちのキュートな日常を縦型ショート動画フォーマットで展開。開幕テーマはZion.T・SUMINがリアレンジした「おジャ魔女カーニバル!!」新バージョン。"
  },
  // ===== 2026-05-28 MOTION JP =====
  {
    id: "2026-05-28-01",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "三菱地所の住まいリレー ブランドコンセプトムービー",
    creator: "ong_",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=V23JQXZ2oHU",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "https://ong-motion.jp/works/478/",
    publishedDate: "2025-01-11",
    genre: ["CM", "ブランディング"],
    techniques: ["キネティックタイポ", "モーショングラフィクス", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/V23JQXZ2oHU/mqdefault.jpg",
    notes: "三菱地所グループの住宅仲介ブランド「三菱地所の住まいリレー」のリブランディングに際しong_がモーションデザインを担当。次の世代へつなぐ暮らしというブランドメッセージを流麗なキネティックタイポグラフィで体現し、温かみと信頼感を両立した映像設計が光る。VI・空間・Webを横断するリブランディングの核を成すコンセプトムービー。"
  },
  {
    id: "2026-05-28-02",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "KARTE 10周年記念ムービー",
    creator: "ong_（モーションデザイン） / THING MEDIA inc.（ディレクション）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=G4FxpJVuIfc",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "https://eizo100.jp/video/102574",
    publishedDate: "2025-03-12",
    genre: ["モーショングラフィクス", "ブランディング"],
    techniques: ["モーショングラフィクス", "キネティックタイポ"],
    thumbnail: "https://img.youtube.com/vi/G4FxpJVuIfc/mqdefault.jpg",
    notes: "CXプラットフォーム「KARTE」（プレイド社）の創業10周年記念ムービー。ong_がモーションデザインを担当し、カメラが伸び続ける線を追いかけるコンセプトで10年の歩みをシームレスに可視化。ブランドの連続性・成長・つながりを一本の線で体現した映像設計が高く評価され、映像作家100人の2025年注目作に選出された。"
  },
  {
    id: "2026-05-28-03",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "東北楽天ゴールデンイーグルス 2025 ビジュアルデザイン",
    creator: "WOW inc.",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=N2XVT0PQed4",
    creatorUrl: "https://www.w0w.co.jp/",
    articleUrl: "",
    publishedDate: "2025-02-01",
    genre: ["ブランディング", "モーショングラフィクス"],
    techniques: ["モーショングラフィクス", "Vector", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/N2XVT0PQed4/mqdefault.jpg",
    notes: "WOW inc.が東北楽天イーグルス2025シーズンのビジュアルアイデンティティ全体をデザイン。チームカラーのクリムゾンと東北の星空・鷹の力強さを抽象化した流麗なモーション表現でシーズン世界観を構築。仙台拠点も持つWOW inc.が地域への愛着を込めた地元密着型クリエイティブとして、スポーツブランディングにおける映像演出の新基準を打ち立てた。"
  },
  {
    id: "2026-05-28-04",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "WAKO x MITSUKOSHI「GINZA 4, April 1」",
    creator: "WOW inc.",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=c4tgSDpENas",
    creatorUrl: "https://www.w0w.co.jp/",
    articleUrl: "",
    publishedDate: "2026-04-01",
    genre: ["CM", "ブランディング"],
    techniques: ["モーショングラフィクス", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/c4tgSDpENas/mqdefault.jpg",
    notes: "銀座4丁目の「和光」と「三越」が2026年4月1日に初コラボした映像作品をWOW inc.が制作。日本百貨店文化を象徴する両ブランドが手を組んだ歴史的な共同制作で、春の銀座の華やかさを精緻な映像美で表現。ラグジュアリーブランドフィルムとしてのクオリティを追求しながら、百貨店の品格と親しみやすさを融合させた高完成度の作品。"
  },
  {
    id: "2026-05-28-05",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "日テレNEWS NNN 5秒PR",
    creator: "ong_",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Ol0Yc4YiVg0",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2025-04-01",
    genre: ["ロゴモーション", "モーショングラフィクス"],
    techniques: ["タイポグラフィ", "キネティックタイポ", "ロゴモーション"],
    thumbnail: "https://img.youtube.com/vi/Ol0Yc4YiVg0/mqdefault.jpg",
    notes: "日本テレビ系列全30局ニュースネットワーク「日テレNEWS NNN」の5秒ブランドPR映像をong_が手がけた。「NNN」のロゴとタイポグラフィを力強いモーションで昇華させ、報道ブランドの信頼感と瞬発力を5秒に凝縮。短尺ながらブランドアイデンティティを最大限に伝えるong_のロゴモーション設計力が際立つ、テレビブランディングムービーの傑作。"
  },
  {
    id: "2026-05-28-06",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "『パワフルプロ野球2026-2027』オープニングムービー",
    creator: "KOO-KI（空気株式会社）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=wOjrANePk1c",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://eizo100.jp/video/103855",
    publishedDate: "2026-04-24",
    genre: ["3DCG", "タイトル/OP"],
    techniques: ["NPR", "セルシェード", "3DCG", "アニメーション"],
    thumbnail: "https://img.youtube.com/vi/wOjrANePk1c/mqdefault.jpg",
    notes: "コナミデジタルエンタテインメントの国民的野球ゲーム最新作のOPムービーをKOO-KIが企画・制作。サクセスモード30周年を記念し30年間ライバルだったキャラたちが日本代表として初共闘する感動のストーリーを展開。NPR/セルシェードで野球の疾走感を圧倒的に再現し、「歴史（サクセス）は、受け継がれる」テーマを映像美で体現した傑作OP。"
  },
  {
    id: "2026-05-28-07",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "星野源 - Star [Official Video]",
    creator: "岡本太玖斗（監督・編集） / 小林由紀野（グラフィックデザイン）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=SaMza0m209g",
    creatorUrl: "https://x.com/takuto_okamoto_",
    articleUrl: "https://artscape.jp/article/55393/",
    publishedDate: "2025-05-14",
    genre: ["MV", "モーショングラフィクス"],
    techniques: ["キネティックタイポ", "日本語タイポ", "タイポグラフィ", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/SaMza0m209g/mqdefault.jpg",
    notes: "アルバム「Gen」収録「Star」のMVは岡本太玖斗が監督・編集を担当。歌詞が空中に浮かび上がるフローティング・タイポグラフィ手法で文字が意味ではなくリズムとして機能する独自の映像文法を確立。artscapeで2回にわたり評論が掲載されるなどモーションデザイン界隈でも高評価を受け、日本語タイポグラフィを主役に据えたMVの新地平を切り開いた。"
  },
  {
    id: "2026-05-28-08",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "Adobe Summit 2025 Sphere Experience – Video World",
    creator: "CEKAI（井口皓太 クリエイティブディレクション）",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1074193826",
    creatorUrl: "https://kotaiguchi.jp/",
    articleUrl: "https://blog.adobe.com/jp/publish/2025/05/12/cc-japanese-creators-challenge-behind-adobe-summit-giant-sphere-ad",
    publishedDate: "2025-03-18",
    genre: ["モーショングラフィクス", "実験的"],
    techniques: ["モーショングラフィクス", "3DCG", "パーティクル", "AI生成"],
    thumbnail: "https://vumbnail.com/1074193826.jpg",
    notes: "ラスベガスの巨大球体型LED「Sphere」でAdobe Summit 2025に際し制作された映像シリーズのうちの1本。日本のモーションデザイナー井口皓太（CEKAI）がCDを務め、生成AIで生み出したフレームを球体ゾエトロープに見立てる手法で新たなシネマティック体験を創出。Adobe FireflyとAEを駆使した約20名のチームが制作し、日本発クリエイティブの国際展開を示す象徴的な作品。"
  },
  {
    id: "2026-05-28-09",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "クボタスピアーズ 2025 PV",
    creator: "ong_（モーションデザイン） / 田多見哲也（ディレクション）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=OOJ7IEYBZsg",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "https://eizo100.jp/video/89692",
    publishedDate: "2024-12-01",
    genre: ["ブランディング", "モーショングラフィクス"],
    techniques: ["モーショングラフィクス", "実写合成", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/OOJ7IEYBZsg/mqdefault.jpg",
    notes: "ジャパンラグビーリーグワンのクボタスピアーズ船橋・東京ベイの2025シーズンPV。ong_がモーションデザインを担当し、ボールやボールキャリアー選手を個別にマスクして精緻なグラフィック合成を実現。ラグビーの激しい接触プレーとモーショングラフィックスを融合させた革新的な演出で、スポーツプロモーションビデオにおける映像表現の可能性を広げた。"
  },
  {
    id: "2026-05-28-10",
    date: "2026-05-28",
    type: "video",
    region: "jp",
    title: "AFEELA Prototype 2026 Design Concept Movie",
    creator: "WOW inc. / Sony Honda Mobility（ソニー・ホンダモビリティ）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=tMkmiZS0brQ",
    creatorUrl: "https://www.w0w.co.jp/",
    articleUrl: "https://www.shm-afeela.com/en/news/2026-01-06/",
    publishedDate: "2026-01-06",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "モーショングラフィクス", "モーフィング"],
    thumbnail: "https://img.youtube.com/vi/tMkmiZS0brQ/mqdefault.jpg",
    notes: "ソニー・ホンダモビリティのEVブランド「AFEELA」がCES 2026でワールドプレミアしたコンセプトカーのデザインムービーをWOW inc.が制作。ドライビングが主目的でない次世代モビリティというビジョンを流麗な3DCGモーションで体現し、空間・エンターテイメント・人との共存をテーマに新たな移動体験を映像化。日本発映像スタジオが世界舞台で展開する国際的ブランドフィルムの好例。"
  },
  // ===== 2026-05-27 GRAPHIC JP =====
  {
    id: "2026-05-27-graphic-01",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "Edo Karuta Playing Cards — 江戸かるた トランプ",
    creator: "MILTZ（神窪満）",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/246678795/Edo-Karuta-Playing-Cards",
    creatorUrl: "https://www.behance.net/miltz",
    articleUrl: "",
    publishedDate: "2026-04-03",
    genre: ["タイポグラフィ", "イラスト", "作字"],
    techniques: ["作字", "江戸文字", "髭文字", "手描き"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/projects/404/20adcf246678795.Y3JvcCwxMTc2LDkyMCwxMTAsMA.png",
    notes: "歌舞伎文字・勘亭流・髭文字・角字など江戸期の文字スタイルを重ね合わせてトランプのモチーフに昇華。絵札には松尾芭蕉・勝海舟ら実在の人物が登場し、史実考証と作字美学が高次元で融合。東京・渋谷を拠点に江戸書体×ストリートカリグラフィーで活動するMILTZの集大成的作品。"
  },
  {
    id: "2026-05-27-graphic-02",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "McLAREN F1 × Vuse「Driven by Change 2024」リバリーデザイン",
    creator: "MILTZ（神窪満）",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/218067443/McLAREN-FORMULA-1-TEAM-and-Vuse-Driven-by-Change-2024",
    creatorUrl: "https://www.behance.net/miltz",
    articleUrl: "https://www.mclaren.com/racing/formula-1/2024/japanese-grand-prix/introducing-miltz-the-artist-behind-our-2024-driven-by-change-livery/",
    publishedDate: "2024-04-03",
    genre: ["作字", "タイポグラフィ", "ブランディング"],
    techniques: ["作字", "江戸文字", "髭文字", "手描き", "ポインティリズム"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/be84ca218067443.67d132dba57ff.png",
    notes: "2024年日本GPのマクラーレンMCL38を飾ったリバリーデザイン。雲間から躍り出る龍をF1マシンのスピードに見立て、髭文字の書体感覚で描き上げた。アクリル絵具にポインティリズム手法を組み合わせた原画は迫力満点で、伝統書体と現代アートの橋渡しを担う一作。"
  },
  {
    id: "2026-05-27-graphic-03",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "BON DANCE — MILLENNIUM PARADE タイトル＆札デザイン",
    creator: "MILTZ（神窪満）",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/125385475/BON-DANCE-MILLENNIUM-PARADE-TITLE-FUDA-DESIGN",
    creatorUrl: "https://www.behance.net/miltz",
    articleUrl: "",
    publishedDate: "2021-08-15",
    genre: ["作字", "タイポグラフィ"],
    techniques: ["作字", "江戸文字", "手描き作字", "日本語タイポ"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/fs_webp/c2e688125385475.61180b4b657dc.jpg",
    notes: "常田大希率いるMILLENNIUM PARADEの楽曲「Bon Dance」MV用タイトルロゴ・御札デザイン。墨書きの迫力を活かしながら現代的なコンポジションに仕上げた手描き作字で、盆踊りの霊的世界観と呼応。映像と一体化したMILTZ流江戸作字の代表作として高い評価を受けた。"
  },
  {
    id: "2026-05-27-graphic-04",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "SPBS ブランドリニューアル — 渋谷パブリッシング＆ブックセラーズ",
    creator: "Sitoh inc.",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/159794495/SPBS-Branding-Design",
    creatorUrl: "https://www.behance.net/sitoh",
    articleUrl: "",
    publishedDate: "2022-12-23",
    genre: ["ブランディング", "タイポグラフィ", "サインデザイン"],
    techniques: ["タイポグラフィ重視", "ミニマル", "スイス・グリッド"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/a9420c159794495.63a5b662c9452.jpg",
    notes: "東京・渋谷の人気書店「SPBS（渋谷パブリッシング＆ブックセラーズ）」のブランドリニューアルをSitoh inc.が担当。ロゴタイプ・パッケージ・サインデザイン・書籍まで統一されたシステムが書店文化の豊かさを誠実に表現。余白と書体の緊張感が共存する、日本の書店デザインの新しい基準点。"
  },
  {
    id: "2026-05-27-graphic-05",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "なら国際映画祭2024 コミュニケーションデザイン",
    creator: "Flowplateaux（木村浩康 アートディレクション）",
    platform: "スタジオ公式",
    videoUrl: "https://flowplateaux.com/work/nara-film-fes2024_communication-design/",
    creatorUrl: "https://flowplateaux.com/",
    articleUrl: "",
    publishedDate: "2024-10-01",
    genre: ["ポスター", "キービジュアル", "エディトリアル"],
    techniques: ["タイポグラフィ", "ポスター", "グラフィックシステム"],
    thumbnail: "https://flowplateaux.com/wp-content/uploads/2025/11/01_headder-1200x631.png",
    notes: "川瀬直美が芸術監督を務める第8回なら国際映画祭のビジュアルアイデンティティ。「対話」をテーマに、対比する要素が重なり合うことで多様なコミュニケーションパターンを生み出すデザインシステムを構築。ポスター・パンフレット・Webサイトを一貫した世界観でまとめ上げた総合グラフィックデザイン。"
  },
  {
    id: "2026-05-27-graphic-06",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "Tokyo Festival 2024 ビジュアルアイデンティティ",
    creator: "emuni（村上タカシ・村上雅志）",
    platform: "スタジオ公式",
    videoUrl: "https://emuni.co.jp/works/tokyo-festival-2024/",
    creatorUrl: "https://emuni.co.jp/",
    articleUrl: "",
    publishedDate: "2024-10-01",
    genre: ["ポスター", "キービジュアル", "VI"],
    techniques: ["タイポグラフィ", "多言語レタリング", "ミニマル"],
    thumbnail: "https://cdn.sanity.io/images/gph0f6tw/production/8c9f342ff6289a8d798f9b76bdb3e231ea0fd229-2400x1129.png",
    notes: "舞台芸術の祭典「東京フェスティバル2024」のビジュアルデザイン。多言語タイポグラフィで構成された人体シルエットを大胆な赤で描き、身体表現の本質を5本の線に抽象化。ネガティブスペースを活かしたミニマリズムと多様な言語の重なりが、国際性と身体性を同時に体現する。"
  },
  {
    id: "2026-05-27-graphic-07",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "劇場版 チェンソーマン レゼ篇 キービジュアル",
    creator: "emuni（村上タカシ・村上雅志）",
    platform: "スタジオ公式",
    videoUrl: "https://emuni.co.jp/works/chainsaw-man-reze/",
    creatorUrl: "https://emuni.co.jp/",
    articleUrl: "",
    publishedDate: "2024-09-01",
    genre: ["キービジュアル", "ポスター", "アニメ"],
    techniques: ["グラフィックデザイン", "広告デザイン", "ハイコントラスト"],
    thumbnail: "https://cdn.sanity.io/images/gph0f6tw/production/38f8dd260d1d7964310528520f86131a7e3d2697-1413x2000.jpg",
    notes: "MAPPA制作の劇場版チェンソーマン「レゼ篇」の宣伝美術をemuniが担当。大胆なトリミングと鮮烈な色使いでキャラクターの危うい魅力を引き出したキービジュアルは、アニメ広告の枠を超えたグラフィックデザインとして高評価。渋谷拠点のemuniが誇る洗練された日本式広告グラフィックの最前線。"
  },
  {
    id: "2026-05-27-graphic-08",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "MEDULLA パーソナルヘアケア リブランディング",
    creator: "GIGANTIC（柴田ハル）",
    platform: "スタジオ公式",
    videoUrl: "https://gig-antic.com/medulla",
    creatorUrl: "https://gig-antic.com/",
    articleUrl: "",
    publishedDate: "2022-04-01",
    genre: ["ブランディング", "パッケージ", "VI"],
    techniques: ["ブランドアイデンティティ", "パッケージデザイン", "フォトモンタージュ"],
    thumbnail: "https://cdn.myportfolio.com/903aca3b828d9df0af1c39100895b290/41a2d888-8595-4f07-946a-b5f9ed1c551d_rwc_141x0x1637x1280x32.jpg",
    notes: "パーソナライズヘアケアブランドMEDULLAの全面リブランディング。7色の香りラインナップにそれぞれキャラクター性を持たせ、花卉フォトグラフィーと組み合わせてなりたい自分像を表現する洗練されたビジュアル体系を構築。Cannes Lions Gold・D&AD Yellow Pencilを獲得した国際的評価作。"
  },
  {
    id: "2026-05-27-graphic-09",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "SEARA Japanese Craft Vodka ロゴ＆パッケージデザイン",
    creator: "GIGANTIC（柴田ハル）",
    platform: "スタジオ公式",
    videoUrl: "https://gig-antic.com/seara",
    creatorUrl: "https://gig-antic.com/",
    articleUrl: "",
    publishedDate: "2022-06-01",
    genre: ["ブランディング", "パッケージ", "ロゴ"],
    techniques: ["ロゴデザイン", "パッケージデザイン", "イラストレーション", "カラー戦略"],
    thumbnail: "https://cdn.prod.website-files.com/66d075ab2a5ee747d9f0e18f/66e42b0b0bfb61d285b1cc77_bottle.png",
    notes: "沖縄まさひろ酒造の初ウォッカブランドのロゴとパッケージ。「海と空だけ。」というコンセプトのもと、スカイブルー・ターコイズ・サンライズイエローなど沖縄の自然色彩を5色でボトルに封じ込めた。佐々木カナコのイラストレーションと一体化した南国的かつ洗練されたデザイン。IWC2023 Silver受賞。"
  },
  {
    id: "2026-05-27-graphic-10",
    date: "2026-05-27",
    type: "graphic",
    region: "jp",
    title: "武蔵野美術大学 映像学科 IAS 2024 学科案内",
    creator: "emuni（村上タカシ・村上雅志）",
    platform: "スタジオ公式",
    videoUrl: "https://emuni.co.jp/works/mau-ias-2024/",
    creatorUrl: "https://emuni.co.jp/",
    articleUrl: "",
    publishedDate: "2024-04-01",
    genre: ["エディトリアル", "グラフィック"],
    techniques: ["グラフィックデザイン", "タイポグラフィ重視", "広告デザイン"],
    thumbnail: "https://cdn.sanity.io/images/gph0f6tw/production/ff1aa245bcd8d3bd520ff12090865e81c784451d-2000x2000.jpg",
    notes: "武蔵野美術大学映像学科の2024年度学科案内DM。映像・メディアを学ぶ学科らしく、視覚的な驚きと情報の明快さを両立したグラフィックデザイン。emuniが得意とする大胆なタイポグラフィと余白使いが際立ち、アカデミック機関のコミュニケーションデザインとして国内デザイン賞に入選。"
  },
  // ===== 2026-05-26 MOTION =====
  {
    id: "2026-05-26-jp-01",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "PAL CLOSET「パルクロ春一番 2026」Web CM",
    creator: "ong_",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=4zGPUmajdrQ",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2026-03-01",
    genre: ["CM"],
    techniques: ["キネティックタイポ", "タイポグラフィ", "作字"],
    thumbnail: "https://img.youtube.com/vi/4zGPUmajdrQ/mqdefault.jpg",
    notes: "ong_が手がけたパルコのレディースブランド「PAL CLOSET」春CMシリーズ最新作。文字が踊るように動くキネティックタイポグラフィで季節感と高揚感を演出。日本語のリズムとデザインを最大限に引き出すong_流モーション設計は国内CMモーションの最前線。"
  },
  {
    id: "2026-05-26-jp-02",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "GUNZE「読めない、GUNZE。」書道篇 — 130周年記念 Web CM",
    creator: "KOO-KI（空気株式会社）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=NJPwkBNe9U8",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://www.gunze.co.jp/corporate/news/2026/02/20260204001.html",
    publishedDate: "2026-02-04",
    genre: ["CM", "ブランディング"],
    techniques: ["作字", "日本語タイポ"],
    thumbnail: "https://img.youtube.com/vi/NJPwkBNe9U8/mqdefault.jpg",
    notes: "グンゼ創業130周年キャンペーン「読めない、GUNZE。」書道篇。一流書道家の達筆で「グンゼ」を書き上げると、その美しい筆記体が逆に一般人には読みにくいという逆説を軽妙に描く。企業名の認知度という課題をコンセプチュアルな作字演出で解決した秀逸なCM。KOO-KIの遊び心あるアイデアと映像技術が光る。"
  },
  {
    id: "2026-05-26-jp-03",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "GUNZE「読めない、GUNZE。」視力検査篇 — 130周年記念 Web CM",
    creator: "KOO-KI（空気株式会社）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LYVMJH47z84",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://www.gunze.co.jp/corporate/news/2026/02/20260204001.html",
    publishedDate: "2026-02-04",
    genre: ["CM", "ブランディング"],
    techniques: ["作字", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/LYVMJH47z84/mqdefault.jpg",
    notes: "同キャンペーンの視力検査篇。眼科の視力検査表スタイルでGUNZEの文字を提示し「読めますか？」と問いかけるユーモラスな演出。書道篇とは正反対のアプローチで同テーマを別角度から攻める二本構成が巧妙。日本語タイポグラフィの認知的面白さを極めたキャンペーンCMの好例。"
  },
  {
    id: "2026-05-26-jp-04",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "にじさんじ「あるてぃめっとくりえいたーず」始動映像",
    creator: "ong_（モーションデザイン） / にじさんじ",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LzxHoNVbgz0",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "",
    publishedDate: "2026-04-01",
    genre: ["ブランディング", "タイトル/OP"],
    techniques: ["キネティックタイポ", "モーショングラフィクス"],
    thumbnail: "https://img.youtube.com/vi/LzxHoNVbgz0/mqdefault.jpg",
    notes: "VTuberグループ「にじさんじ」の新クリエイティブ企画「あるてぃめっとくりえいたーず」始動映像。ong_がDirection・Design・Motion Designを担当したオープニング映像を含む。メンバー自身が動画企画・制作を担うというコンセプトに合わせ、軽快かつ遊び心あるモーション演出を採用。2026年4月1日に公開された話題作。"
  },
  {
    id: "2026-05-26-jp-05",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "サントリー 優しい麦茶「小島よしお リサイクルリサイタル」リリックモーション",
    creator: "ong_ / CHOCOLATE Inc. / GEEK PICTURES Inc.",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=UWdYZWPkHVU",
    creatorUrl: "https://ong-motion.jp/",
    articleUrl: "https://eizo100.jp/video/89686",
    publishedDate: "2024-07-11",
    genre: ["リリックモーション", "CM"],
    techniques: ["リリックモーション", "キネティックタイポ", "作字"],
    thumbnail: "https://img.youtube.com/vi/UWdYZWPkHVU/mqdefault.jpg",
    notes: "小島よしおの代名詞ネタをリサイクルをテーマにリサイタル化したサントリー優しい麦茶のリリックモーション。ong_がポップかつリズミカルなキネティックタイポグラフィを設計し、いつも以上にクールな小島よしおを演出。日本語リリックモーションの手本として国内モーションデザインコミュニティで高く評価された一作。"
  },





  {
    id: "2026-05-26-jp-06",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "GUILTY GEAR -STRIVE- シーズンパス4 第3弾「ユニカ」キャラクタートレーラー",
    creator: "アークシステムワークス（Arc System Works）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=b4zvyc_dxXU",
    creatorUrl: "https://www.guiltygear.com/ggst/jp/",
    articleUrl: "",
    publishedDate: "2025-05-27",
    genre: ["3DCG", "タイトル/OP"],
    techniques: ["NPR", "セルシェード", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/b4zvyc_dxXU/mqdefault.jpg",
    notes: "横浜のアークシステムワークスが誇るアニメルック3DCGの極致。旧来のGGXXシリーズから「アニメを超えるアニメCG」を追求してきた同社の技術が最新DLCキャラクター「ユニカ」で再び輝く。手描きラインの質感・セルシェードの陰影・流麗なアクションモーションが完璧に融合し、NPR/セルシェード3DCGの世界的模範事例として国内外のCGクリエイターから称賛を集め続ける。"
  },
  {
    id: "2026-05-26-jp-07",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "ドラゴンボール Sparking! ZERO ローンチトレーラー",
    creator: "Spike Chunsoft / バンダイナムコエンターテインメント",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=pgdJm0t3Das",
    creatorUrl: "https://www.bandainamcoent.co.jp/",
    articleUrl: "",
    publishedDate: "2024-10-10",
    genre: ["3DCG", "CM"],
    techniques: ["NPR", "セルシェード", "3DCG"],
    thumbnail: "https://img.youtube.com/vi/pgdJm0t3Das/mqdefault.jpg",
    notes: "スパイク・チュンソフト開発・バンダイナムコ発売の対戦格闘ゲーム最新作のローンチトレーラー。PS5世代に刷新されたセルシェードNPR表現は劇場版ドラゴンボールの作画を超えるクオリティと評され世界を驚かせた。180キャラクター超の超絶アクションをNPR全開で詰め込んだ映像は、日本産セルシェードゲームグラフィックスが到達した一つの頂点を示す。"
  },
  {
    id: "2026-05-26-jp-08",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "ONE OK ROCK - C.U.R.I.O.S.I.T.Y. feat. Paledusk and CHICO CARLITO [Official Music Video]",
    creator: "ONE OK ROCK / maxilla（Masaki Watanabe監督）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=EPlFuHhE05g",
    creatorUrl: "https://maxilla.jp/",
    articleUrl: "",
    publishedDate: "2025-04-17",
    genre: ["MV"],
    techniques: ["実写合成", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/EPlFuHhE05g/mqdefault.jpg",
    notes: "国内外で活躍するロックバンドONE OK ROCKが国内ラッパーPaledusk・CHICO CARLITOを迎えた新曲のMV。東京のクリエイティブスタジオmaxillaのMasaki Watanabe監督が全体のビジュアルデザインとモーション設計を担当。maxillaならではのスタイリッシュな映像言語が楽曲のアグレッシブなエネルギーと融合し、2025年春のJ-Rock MVとして高い注目を集めた。"
  },
  {
    id: "2026-05-26-jp-09",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "Lazarus - Opening Sequence feat. 「VORTEX」 by Kamasi Washington",
    creator: "MAPPA",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=XBMrH1ZQs90",
    creatorUrl: "https://www.mappa.co.jp/",
    articleUrl: "https://www.crunchyroll.com/news/latest/2025/3/27/lazarus-opening-movie-anime-shinichiro-watanabe",
    publishedDate: "2025-03-27",
    genre: ["タイトル/OP", "アニメーション"],
    techniques: ["タイポグラフィ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/XBMrH1ZQs90/mqdefault.jpg",
    notes: "渡辺信一郎監督×MAPPAの新アニメ「Lazarus」のオープニング映像。カウボーイビバップを彷彿とさせるグランジ体タイポグラフィが宇宙を落下するキャラクターシルエットと共鳴する大胆な構成。Kamasi Washingtonによるジャズ主題歌「VORTEX」との相乗効果が圧巻で、タイポグラフィとモーションを主軸に置くアニメOPの新形式を示した作品として国内外のモーションデザイナーから高く評価された。"
  },
  {
    id: "2026-05-26-jp-10",
    date: "2026-05-26",
    type: "video",
    region: "jp",
    title: "SIRUP - KIRA KIRA (Official Music Video)",
    creator: "SIRUP",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=_JLwkJGVeqk",
    creatorUrl: "https://sirup.online/",
    articleUrl: "https://www.billboard-japan.com/d_news/detail/153589/2",
    publishedDate: "2025-09-03",
    genre: ["MV"],
    techniques: ["実写合成"],
    thumbnail: "https://img.youtube.com/vi/_JLwkJGVeqk/mqdefault.jpg",
    notes: "サイバーパンクな世界を舞台にSIRUPが一人三役を演じる3rdアルバム「OWARI DIARY」のリードトラックMV。疾走するバイク・政治演説・未来CMキャラクターと瞬時に役を変えながら都市の夜の煌めきと逃避衝動を描く。maxillaがアルバムアートワーク全体のアートディレクションを担当したことで映像・ジャケット・物販が一貫した世界観を共有し、トータルコミュニケーション設計として完成度が高い。"
  },
  // ===== 2026-05-26 GRAPHIC JP =====
  {
    id: "2026-05-26-graphic-jp-01",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "作字(SAKUJI) — typography study",
    creator: "Kisuke Ohta",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/43665761/(SAKUJI)-typography-study",
    creatorUrl: "https://www.behance.net/kisuke",
    articleUrl: "",
    publishedDate: "2016-01-01",
    genre: ["タイポグラフィ"],
    techniques: ["作字", "日本語タイポ"],
    thumbnail: "https://i.pinimg.com/736x/f1/b2/1f/f1b21fbf1074ff5bd6c45ef182a4f9a7.jpg",
    notes: "東京のグラフィックデザイナー・Kisuke Ohtaによる作字スタイル研究の集大成。ゴシック・明朝・装飾的バリエーションまで漢字の骨格を解析・再構築し、無数の字体を展開する。書体設計と作字の境界を探る実験的アーカイブとして現在もPinterest上で国内外のデザイナーに広く参照され続けている定番作。"
  },
  {
    id: "2026-05-26-graphic-jp-02",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "KAGUWA — Japanese Black Tea Branding",
    creator: "Koyuki Inagaki",
    platform: "Behance",
    videoUrl: "https://www.behance.net/gallery/226119129/KAGUWA",
    creatorUrl: "https://www.behance.net/koyukiinagaki",
    articleUrl: "",
    publishedDate: "2025-05-17",
    genre: ["ブランディング", "パッケージ"],
    techniques: ["ミニマル", "日本語タイポ"],
    thumbnail: "https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/672445226119129.6828ead9d29f0.jpg",
    notes: "東京在住デザイナーが手がけた日本産純粋紅茶ブランド「KAGUWA」のブランディング。ひらがなの曲線を想起させるロゴタイプが和と洋の均衡を象徴し、必要最小限の装飾で茶葉本来の香りを視覚化。小ぶりな缶とタグの造形と相まって、モダンな日本らしさを体現したパッケージデザイン。"
  },
  {
    id: "2026-05-26-graphic-jp-03",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "SENSE ISLAND/LAND 2024 — コミュニケーションデザイン",
    creator: "Flowplateaux (木村浩康 + 藤井かおり) / Panoramatiks",
    platform: "Flowplateaux",
    videoUrl: "https://flowplateaux.com/en/work/sense-island-land-2024_communication-design/",
    creatorUrl: "https://flowplateaux.com/en/",
    articleUrl: "",
    publishedDate: "2025-11-05",
    genre: ["ポスター", "ブランディング", "サインデザイン"],
    techniques: ["タイポグラフィ重視", "ミニマル"],
    thumbnail: "https://flowplateaux.com/wp-content/uploads/2025/10/SSL_FPX-1200x625.png",
    notes: "横須賀の没入型アートフェスティバル「SENSE ISLAND/LAND 2024」のコミュニケーションデザイン。モールス信号のリズムを基軸に、メディアと視距離で変容する柔軟なビジュアルシステムを構築。DFA Design for Asia 2025 Gold Award・東京ADC Award 2025・Japan Typography Annual 2026 審査員賞を達成した国内トップスタジオ作。"
  },
  {
    id: "2026-05-26-graphic-jp-04",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "田部井美奈「光と図形と、その周辺」",
    creator: "田部井美奈 / Mina Tabei",
    platform: "Ginza Graphic Gallery",
    videoUrl: "https://www.dnpfcp.jp/gallery/ggg/jp/00000848",
    creatorUrl: "https://www.instagram.com/mina_tabei/",
    articleUrl: "",
    publishedDate: "2025-09-05",
    genre: ["ポスター"],
    techniques: ["幾何学", "モノクロ", "ハイコントラスト"],
    thumbnail: "https://www.adfwebmagazine.jp/wp-content/uploads/2025/08/adf-web-magazine-mina-tabei-ggg-1.jpg",
    notes: "ギンザ・グラフィック・ギャラリー第409回企画展。2018年以来追求してきた実験作「光と図形」の最新シリーズを空間ごと体験できる形で発表。光と影・三次元の偶然性を二次元の紙面に定着させた独自の幾何学表現で、第28回亀倉雄策賞・JAGDA Award 2026をW受賞。"
  },
  {
    id: "2026-05-26-graphic-jp-05",
    date: "2026-05-26",
    type: "graphic",
    region: "jp",
    title: "GRAPHIC TRIAL 2025 -FIND-",
    creator: "大貫卓也 / 関本明子 / 吉本英樹 / 妹尾琢史 × TOPPAN",
    platform: "TOPPAN",
    videoUrl: "https://www.toppan.com/ja/joho/gainfo/graphictrial/2025/",
    creatorUrl: "https://www.toppan.com/ja/joho/gainfo/graphictrial/2025/creator/",
    articleUrl: "",
    publishedDate: "2025-04-12",
    genre: ["ポスター"],
    techniques: ["タイポグラフィ重視", "ハイコントラスト"],
    thumbnail: "",
    notes: "TOPPANと国内トップクリエイター4名が協働するポスター展覧会「グラフィックトライアル」第19回。テーマ「FIND」のもと、大貫卓也がレンチキュラー大判印刷の空間体験、関本明子がインク重ね刷りの色彩の謎を探究。活版・スクリーン・インクジェットなど最先端技術とグラフィックデザインが融合した印刷表現の最前線。"
  },
  // ===== 2026-05-22 GRAPHIC (cleared - articles only, will be re-populated via Run now with Pinterest-style sources) =====
  // ===== 2026-05-22 MOTION =====
  {
    id: "2026-05-22-jp-01",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "Nintendo Switch 2 – Overview Trailer",
    creator: "Nintendo",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=9flte56erE8",
    creatorUrl: "https://www.nintendo.co.jp/",
    articleUrl: "",
    publishedDate: "2025-01-16",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/9flte56erE8/mqdefault.jpg",
    notes: "任天堂が2025年1月16日にサプライズ公開したNintendo Switch 2の公式オーバービュートレーラー。実写とCGを組み合わせた洗練されたプロダクト映像で、Joy-Con 2の磁気アタッチメント・マウスモードなど新機能を直感的に伝える構成が見事。初日4800万再生を記録し、世界的ゲームハードローンチにおける映像コミュニケーション設計の模範例として高く評価された。"
  },
  {
    id: "2026-05-22-jp-02",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "米津玄師「IRIS OUT」Official Music Video",
    creator: "米津玄師 / 劇場版チェンソーマン レゼ篇",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LmZD-TU96q4",
    creatorUrl: "https://www.youtube.com/channel/UCUCeZaZeJbEYAAzvMgrKOPQ",
    articleUrl: "",
    publishedDate: "2025-09-15",
    genre: ["MV", "アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/LmZD-TU96q4/mqdefault.jpg",
    notes: "劇場版『チェンソーマン レゼ篇』主題歌。Spotify Japan史上最多ストリーム初日記録を更新し、2026年5月現在もBillboard JAPAN Hot Animation 1位をキープするロングラン。劇場映像とアニメーションの緩急あるカット割りと楽曲の疾走感が完璧に噛み合う。"
  },
  {
    id: "2026-05-22-jp-03",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "ヨルシカ「へび」OFFICIAL VIDEO",
    creator: "ヨルシカ / 佐藤美代",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=sf0QFJTvOLM",
    creatorUrl: "https://yorushika.com/",
    articleUrl: "https://realsound.jp/2025/02/post-1938409.html",
    publishedDate: "2025-01-17",
    genre: ["MV", "アニメーション"],
    techniques: ["ストップモーション", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/sf0QFJTvOLM/mqdefault.jpg",
    notes: "TVアニメ『チ。―地球の運動について―』新エンディングテーマ。アニメーター佐藤美代が手がけたサンドアニメーション＋ペインティング・オン・グラスによる繊細な映像。記憶と風景が砂の粒子とともに溶け合うような独自の質感が唯一無二で、国内アニメMV屈指の完成度。"
  },
  {
    id: "2026-05-22-jp-04",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "初星学園「Wildest Flower」 — Character Animation Film",
    creator: "大橋隆之 / CALF（学園アイドルマスター）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=iiiLtE4w2pE",
    creatorUrl: "https://www.behance.net/ohashitakashi",
    articleUrl: "https://www.stashmedia.tv/takashi-ohashi-calf-plant-the-wildest-flower-for-hatsuboshi-gakuen-in-new-music-video/",
    publishedDate: "2026-03-19",
    genre: ["アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/iiiLtE4w2pE/mqdefault.jpg",
    notes: "学園アイドルマスターの花海咲季（元アスリート転向アイドル）をフィーチャーした楽曲のキャラクターアニメーション映像。CALF所属の大橋隆之監督が担当しSTASHメディアに特集された鮮烈な色彩設計とダイナミックな作画が圧巻。ゲームキャラクターの覚醒をフルアニメーションで描き、日本のキャラクターアニメーション制作の現在地を示す傑作。"
  },
  {
    id: "2026-05-22-jp-05",
    date: "2026-05-22",
    type: "video",
    region: "jp",
    title: "劇場版チェンソーマン レゼ篇 — Official Trailer",
    creator: "MAPPA",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=tAzAhDNdehs",
    creatorUrl: "https://www.mappa.co.jp/",
    articleUrl: "https://www.crunchyroll.com/news/latest/2025/10/13/chainsaw-man-the-movie-reze-arc-unveils-explosive-new-trailer",
    publishedDate: "2025-07-04",
    genre: ["アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/tAzAhDNdehs/mqdefault.jpg",
    notes: "MAPPAが制作した劇場版チェンソーマン『レゼ篇』公式トレーラー（Anime Expo 2025解禁）。2025年9月19日日本公開・10月24日米国公開。爆弾娘レゼとデンジの激戦をMAPPA渾身のアクション作画で描き、劇場版アニメのトレーラーとして構成面でも完成度が高い。米津玄師主題歌との相乗効果もあり2025年の国産劇場版アニメを代表する一作。"
  },





  // ===== 2026-05-21 =====
  {
    id: "2026-05-21-jp-01",
    date: "2026-05-21",
    region: "jp",
    title: "AFEELA Prototype 2026 | Concept Movie",
    creator: "WOW inc. / Sony Honda Mobility",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=tMkmiZS0brQ",
    creatorUrl: "https://www.w0w.co.jp/en/",
    articleUrl: "https://www.shm-afeela.com/en/news/2026-01-06/",
    publishedDate: "2026-01-06",
    genre: ["ブランディング", "3DCG"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/tMkmiZS0brQ/mqdefault.jpg",
    notes: "ソニー・ホンダモビリティのEV『AFEELA』がCES 2026でワールドプレミアした際の公式コンセプトムービー。東京のビジュアルデザインスタジオWOW inc.が手がけた3DCGと動的UIアニメーションの融合映像で、車体フォルムとデジタルインターフェースが有機的に絡み合う。モビリティの未来を高い審美眼で提示した意欲的なブランドフィルム。"
  },
  {
    id: "2026-05-21-jp-02",
    date: "2026-05-21",
    region: "jp",
    title: "MULTRA Brand Film",
    creator: "MULTRA Inc.",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1135619204",
    creatorUrl: "https://vimeo.com/multra",
    articleUrl: "https://www.stashmedia.tv/multra-studio-makes-stash-debut-with-new-brand-film/",
    publishedDate: "2025-10-01",
    genre: ["ブランディング", "モーショングラフィクス"],
    techniques: ["2Dアニメーション", "モーフィング"],
    thumbnail: "https://vumbnail.com/1135619204.jpg",
    notes: "東京のモーションデザインスタジオMULTRAによるSTASHデビュー自主制作ブランドフィルム。ジャズィーなリズムとともに多様なクリエイティブアイデアが連続・変容するマルチメディア表現。手描きキャラクターとグラフィックモーションがシームレスに融合し、スタジオのクリエイティブDNAを余すところなく体現する。"
  },
  {
    id: "2026-05-21-jp-03",
    date: "2026-05-21",
    region: "jp",
    title: "パワフルプロ野球2026-2027 オープニングムービー",
    creator: "KOO-KI x Konami Digital Entertainment",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=wOjrANePk1c",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://koo-ki.co.jp/works/detail/pawa-2026-2027",
    publishedDate: "2026-03-12",
    genre: ["タイトル/OP", "3DCG"],
    techniques: ["3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/wOjrANePk1c/mqdefault.jpg",
    notes: "野球ゲームシリーズ30周年を飾るオープニングムービー。福岡の映像集団KOO-KIが歴代WBC名場面をリイマジネーションし、イチロー・大谷翔平ら伝説的選手が集結するダイナミックな3DCGシーンを展開。スポーツゲームOPの域を超えた映像クオリティは国内外のゲームファン・映像ファンから高い評価を受ける。"
  },
  {
    id: "2026-05-21-jp-04",
    date: "2026-05-21",
    region: "jp",
    title: "HIDARI（ひだり） - ストップモーション侍映画 パイロット版",
    creator: "Whatever Co. / dwarf studios / TECARAT（川村真司監督）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=DpefYPLH67A",
    creatorUrl: "https://whatever.co/work/hidari/",
    articleUrl: "https://variety.com/2026/film/global/keanu-reeves-voice-lead-stop-motion-samurai-film-hidari-1236751402/",
    publishedDate: "2023-03-27",
    genre: ["アニメーション"],
    techniques: ["ストップモーション"],
    thumbnail: "https://img.youtube.com/vi/DpefYPLH67A/mqdefault.jpg",
    notes: "全キャラクターを木から手彫りしフレームごとに動かすストップモーション時代劇の短編パイロット版。4.9M再生を突破し2026年5月カンヌAnnecy Showcaseへ選出。同月キアヌ・リーブスのリード声優起用が発表され再び世界から注目を集めた、日本の手仕事アニメーションの金字塔。"
  },
  {
    id: "2026-05-21-jp-05",
    date: "2026-05-21",
    region: "jp",
    title: "Ado「ビバリウム」Official Music Video",
    creator: "林響太朗 / ACROBAT FILM",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=YvYii6dluM8",
    creatorUrl: "https://www.universal-music.co.jp/ado/",
    articleUrl: "https://natalie.mu/music/news/662104",
    publishedDate: "2026-02-28",
    genre: ["MV"],
    techniques: ["実写合成"],
    thumbnail: "https://img.youtube.com/vi/YvYii6dluM8/mqdefault.jpg",
    notes: "Ado初の完全実写MV。自身の半生をテーマにした楽曲に合わせ林響太朗監督が300カット超の迫力映像を構築した意欲作。水中撮影・逆光シルエット・ハイヒール疾走など多彩な手法を組み合わせ、Adoの感情の振れ幅を余すところなく映像化。日本音楽MVの新境地として各メディアが絶賛した2026年の注目作。"
  },





];
