/* ========================================
   Daily Motion Graphics Picks — Data
   ----------------------------------------
   このファイルは毎朝10時のスケジュールタスクが自動更新します。
   手動でも編集可能（フォーマットを保つこと）。

   各エントリのスキーマ:
   {
     id: "YYYY-MM-DD-jp-01",       // ユニークID
     date: "YYYY-MM-DD",           // ピックアップ日
     region: "jp" | "global",       // 国内 / 海外
     title: "作品タイトル",
     creator: "制作者・スタジオ名",
     platform: "YouTube",          // YouTube / Vimeo / X / TikTok / Behance 等
     videoUrl: "https://...",      // 動画本体URL
     creatorUrl: "https://...",    // 制作者ページURL（任意）
     articleUrl: "",               // 関連記事URL（任意）
     publishedDate: "YYYY-MM-DD",  // 作品の公開日
     genre: ["MV", "モーショングラフィクス"],
     techniques: ["3DCG", "タイポグラフィ"],
     thumbnail: "https://...",     // サムネイルURL（YouTube: https://img.youtube.com/vi/{ID}/mqdefault.jpg）
     notes: "注目ポイント（2-3行）"
   }
   ======================================== */

window.picksData = [
  // ===== 2026-05-22 GRAPHIC =====
  {
    id: "2026-05-22-graphic-jp-01",
    date: "2026-05-22",
    type: "graphic",
    region: "jp",
    title: "光と図形と、その周辺",
    creator: "田部井美奈",
    platform: "JAGDA",
    videoUrl: "https://www.jagda.or.jp/news/10088/",
    creatorUrl: "https://artscape.jp/exhibitions/48229/",
    articleUrl: "https://www.axismag.jp/posts/2026/02/700968.html",
    publishedDate: "2025-12-01",
    genre: ["ポスター"],
    techniques: ["ミニマル", "幾何学"],
    thumbnail: "",
    notes: "第28回亀倉雄策賞とJAGDA賞2026の二冠を受賞した作品・個展シリーズ。光と幾何学形態を繊細に組み合わせたコンポジションが特徴で、個展の作品・空間構成・告知ツール・作品集が総合評価された。選考委員から『凛とした品位のなかに明るいやさしさ』を持つと評された、国内グラフィックデザインの最高峰。"
  },
  {
    id: "2026-05-22-graphic-jp-02",
    date: "2026-05-22",
    type: "graphic",
    region: "jp",
    title: "横浜美術館リニューアル VI・サイン・空間構築",
    creator: "菊地敦己 / Bluemark",
    platform: "JAGDA",
    videoUrl: "https://yokohama.art.museum/",
    creatorUrl: "",
    articleUrl: "https://www.jagda.or.jp/news/10093/",
    publishedDate: "2025-03-26",
    genre: ["ブランディング", "サインデザイン"],
    techniques: ["ミニマル"],
    thumbnail: "",
    notes: "建築家・乾久美子と協働した横浜美術館リニューアルのVI・サイン・空間構築でJAGDA賞2026複合部門を受賞。リニューアルロゴから無料開放エリア『じゆうエリア』のサイン計画まで一貫したデザイン言語を構築し、建築とグラフィックの連携による高い完成度が評価された。"
  },
  {
    id: "2026-05-22-graphic-jp-03",
    date: "2026-05-22",
    type: "graphic",
    region: "jp",
    title: "コクヨ CIリニューアル 好奇心を人生に",
    creator: "コクヨ デザイン本部",
    platform: "公式サイト",
    videoUrl: "https://www.kokuyo.com/magazine/kokuyo/special-ci-renewal/",
    creatorUrl: "https://www.kokuyo.co.jp/",
    articleUrl: "https://www.jagda.or.jp/news/10093/",
    publishedDate: "2025-10-02",
    genre: ["ブランディング", "ロゴ"],
    techniques: ["ミニマル", "幾何学", "スイス・グリッド"],
    thumbnail: "",
    notes: "創業120周年を機に刷新されたコーポレートアイデンティティ。K・K・Yの3文字を等間隔の斜めラインで整列させた新ロゴは並べ方・組み合わせ方で無限のパターンを生成し、コーポレートメッセージ『好奇心を人生に』とともに名刺から測量野帳・Webまで全社展開。JAGDA賞2026 CI/VI部門を受賞した。"
  },
  {
    id: "2026-05-22-graphic-jp-04",
    date: "2026-05-22",
    type: "graphic",
    region: "jp",
    title: "ヒロシマ・アピールズ 2025",
    creator: "北川一成 / GRAPH",
    platform: "JAGDA",
    videoUrl: "https://bijutsutecho.com/magazine/news/exhibition/31026",
    creatorUrl: "https://www.moshi-moshi.jp/",
    articleUrl: "https://www.advertimes.com/20250806/article507557/",
    publishedDate: "2025-07-09",
    genre: ["ポスター"],
    techniques: ["ミニマル", "モノクロ", "タイポグラフィ重視"],
    thumbnail: "",
    notes: "戦後80年の節目に制作されたJAGDA年次平和ポスター。白の空間に黒文字で『PEACE』を記した両面構造で、余白の多層的な意味を静かに視覚化。広島市内26か所のバス停に掲示され、美術手帖・AdverTimes等各メディアが取り上げた。北川一成ならではの削ぎ落とされた造形言語が際立つ傑作。"
  },
  {
    id: "2026-05-22-graphic-jp-05",
    date: "2026-05-22",
    type: "graphic",
    region: "jp",
    title: "永井一正作品集 LIFE",
    creator: "永井一正 / 六耀社",
    platform: "JAGDA",
    videoUrl: "https://www.jagda.or.jp/news/10093/",
    creatorUrl: "",
    articleUrl: "https://www.adfwebmagazine.jp/en/design/kamekura-award-2026-jagda-awards/",
    publishedDate: "2025-06-01",
    genre: ["装丁", "エディトリアル"],
    techniques: ["ミニマル", "ハイコントラスト"],
    thumbnail: "",
    notes: "日本グラフィックデザインの巨匠・永井一正の生涯作品を集成したモノグラフ作品集でJAGDA賞2026複合部門を受賞。自然・生命を主題にした象徴的ポスターの数々を高品質な印刷で収録し、半世紀以上にわたるデザイン思想の変遷を一冊で俯瞰できる、国内グラフィックデザイン史に残る刊行物。"
  },
  {
    id: "2026-05-22-graphic-global-01",
    date: "2026-05-22",
    type: "graphic",
    region: "global",
    title: "BBH Rebrand — Zag Identity & Bespoke Typeface",
    creator: "BBH / Studio Drama",
    platform: "It's Nice That",
    videoUrl: "https://www.itsnicethat.com/articles/bbh-studio-drama-rebrand-graphic-design-project-260226",
    creatorUrl: "https://www.bbh.co.uk/",
    articleUrl: "https://www.creativereview.co.uk/bbh-agency-new-visual-identity-typefaces-sheep-ad/",
    publishedDate: "2026-02-11",
    genre: ["ブランディング", "タイポグラフィ"],
    techniques: ["タイポグラフィ重視"],
    thumbnail: "",
    notes: "44年ぶりの大改革。3創業者の性格を反映した3ウェイトのオーダーメイド書体（Bartle / Bogle / Hegarty）が中核で、独自の『Zag』グリフが差異の表現を可能にする。Googleフォントとしてオープンソース公開後わずか数か月で400万ダウンロード突破。タイポグラフィ主導のブランド刷新の好例として業界各誌が高く評価。"
  },
  {
    id: "2026-05-22-graphic-global-02",
    date: "2026-05-22",
    type: "graphic",
    region: "global",
    title: "The Mosaic Rooms — Visual Identity",
    creator: "Samar Maakaroun / Pentagram London",
    platform: "It's Nice That",
    videoUrl: "https://www.itsnicethat.com/articles/samar-maakaroun-the-mosaic-rooms-identity-graphic-design-project-060526",
    creatorUrl: "https://www.pentagram.com/",
    articleUrl: "https://www.creativeboom.com/news/why-pentagrams-samar-maakaroun-designed-a-logo-that-just-wont-settle/",
    publishedDate: "2026-02-01",
    genre: ["ブランディング", "ロゴ"],
    techniques: ["タイポグラフィ重視", "幾何学"],
    thumbnail: "",
    notes: "ロンドンのSWANA（西南アジア・北アフリカ）文化スペースのリブランド。MとRを融合させたモノグラムは右から左・左から右へと同時に流れ、言語・場所・アイデンティティの間を往来する存在を視覚化。ダスティピンクのパレットが政治的権威の言語から逸脱し、2026年5月にIt's Nice Thatが特集した意欲作。"
  },
  {
    id: "2026-05-22-graphic-global-03",
    date: "2026-05-22",
    type: "graphic",
    region: "global",
    title: "LA28 — Look of the Games LA in Full Bloom",
    creator: "LA28 Design Team",
    platform: "Creative Review",
    videoUrl: "https://www.creativereview.co.uk/la28-olympic-paralympic-look-of-the-games-2028/",
    creatorUrl: "https://la28.org/",
    articleUrl: "https://la28.org/en/newsroom/la28-debuts-the-official-look-of-the-games.html",
    publishedDate: "2026-03-01",
    genre: ["ブランディング", "ポスター"],
    techniques: ["グラデーション", "幾何学", "スイス・グリッド"],
    thumbnail: "",
    notes: "2028年ロサンゼルス五輪の公式ビジュアルアイデンティティ。カリフォルニアのスーパーブルームをモチーフにした13パターンの『ブルーム』をモジュラー12行グリッドで組み合わせ、スタジアム外壁から選手証まで一貫スケールを実現。LAの街路標識にインスパイアされた4書体とバード・オブ・パラダイスカラーが融合した大規模スポーツブランディング。"
  },
  {
    id: "2026-05-22-graphic-global-04",
    date: "2026-05-22",
    type: "graphic",
    region: "global",
    title: "Imperial College London — Brand Identity",
    creator: "The Click Design Consultants",
    platform: "It's Nice That",
    videoUrl: "https://www.itsnicethat.com/articles/the-click-imperial-college-london-graphic-design-project-200526",
    creatorUrl: "",
    articleUrl: "",
    publishedDate: "2026-05-20",
    genre: ["ブランディング"],
    techniques: ["タイポグラフィ重視", "ミニマル"],
    thumbnail: "",
    notes: "ロンドンの名門理工系大学のブランドアイデンティティ刷新。『I』の文字にIndividual（個人）・Identity（個性）・Imperial（帝国）の三重の意味を込めた視覚システムが特徴。2026年5月20日のIt's Nice Thatで特集され、教育機関ブランディングにおける新たなコンセプト主導のアプローチとして注目を集めた。"
  },
  {
    id: "2026-05-22-graphic-global-05",
    date: "2026-05-22",
    type: "graphic",
    region: "global",
    title: "COBE Architects — Brand Identity",
    creator: "Alexis Mark",
    platform: "It's Nice That",
    videoUrl: "https://www.itsnicethat.com/articles/alexis-mark-cobe-branding-graphic-design-project-130426",
    creatorUrl: "",
    articleUrl: "",
    publishedDate: "2026-04-13",
    genre: ["ブランディング"],
    techniques: ["タイポグラフィ重視", "ミニマル"],
    thumbnail: "",
    notes: "発車標・時刻表のビジュアル言語からインスピレーションを得た、コペンハーゲンの建築事務所COBEのブランドシステム。モノスペース書体と交通インフラの機能美を融合させた珍しいコンセプトで、建築の都市的・構造的な特質をブランドデザインに昇華させた。It's Nice Thatが2026年4月13日に特集した意欲作。"
  },
  // ===== 2026-05-22 =====
  {
    id: "2026-05-22-jp-01",
    date: "2026-05-22",
    region: "jp",
    title: "ヨルシカ「あぶく」OFFICIAL VIDEO",
    creator: "ヨルシカ / 擬態するメタ（しまぐちニケ + Bivi）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=OHAjc-ayhus",
    creatorUrl: "https://yorushika.com/",
    articleUrl: "https://kai-you.net/article/95295",
    publishedDate: "2026-04-22",
    genre: ["MV", "アニメーション"],
    techniques: ["実写合成", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/OHAjc-ayhus/mqdefault.jpg",
    notes: "TVアニメ『LIAR GAME』OPテーマ。実写と2Dアニメを融合させた「擬態するメタ」が担当。主人公が密室で何度も殺されながら脱出を目指す無限ループ構造に視聴者自身が巻き込まれるメタ的仕掛けが秀逸。公開直後から800万再生超、世界のYouTubeランキングに続々チャートイン。"
  },
  {
    id: "2026-05-22-jp-02",
    date: "2026-05-22",
    region: "jp",
    title: "米津玄師「IRIS OUT」Official Music Video",
    creator: "米津玄師 / 劇場版チェンソーマン レゼ篇",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=LmZD-TU96q4",
    creatorUrl: "https://www.youtube.com/channel/UCUCeZaZeJbEYAAzvMgrKOPQ",
    articleUrl: "",
    publishedDate: "2025-09-15",
    genre: ["MV", "アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/LmZD-TU96q4/mqdefault.jpg",
    notes: "劇場版『チェンソーマン レゼ篇』主題歌。Spotify Japan史上最多ストリーム初日記録を更新し、2026年5月現在もBillboard JAPAN Hot Animation 1位をキープするロングラン。劇場映像とアニメーションの緩急あるカット割りと楽曲の疾走感が完璧に噛み合う。"
  },
  {
    id: "2026-05-22-jp-03",
    date: "2026-05-22",
    region: "jp",
    title: "ヨルシカ「へび」OFFICIAL VIDEO",
    creator: "ヨルシカ / 佐藤美代",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=sf0QFJTvOLM",
    creatorUrl: "https://yorushika.com/",
    articleUrl: "https://realsound.jp/2025/02/post-1938409.html",
    publishedDate: "2025-01-17",
    genre: ["MV", "アニメーション"],
    techniques: ["ストップモーション", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/sf0QFJTvOLM/mqdefault.jpg",
    notes: "TVアニメ『チ。―地球の運動について―』新エンディングテーマ。アニメーター佐藤美代が手がけたサンドアニメーション＋ペインティング・オン・グラスによる繊細な映像。記憶と風景が砂の粒子とともに溶け合うような独自の質感が唯一無二で、国内アニメMV屈指の完成度。"
  },
  {
    id: "2026-05-22-jp-04",
    date: "2026-05-22",
    region: "jp",
    title: "ずっと真夜中でいいのに。「クズリ念」MV",
    creator: "ずっと真夜中でいいのに。 / Waboku",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=ut889MZ9yNo",
    creatorUrl: "https://www.youtube.com/@ZUTOMAYO",
    articleUrl: "https://www.billboard-japan.com/d_news/detail/142886",
    publishedDate: "2024-10-23",
    genre: ["MV", "アニメーション"],
    techniques: ["セルアニメ", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/ut889MZ9yNo/mqdefault.jpg",
    notes: "約4年ぶりにアニメーターWabokuが復帰した話題作。Satomi Tena・minoMi・uiu・uraraら複数アニメーターが参加し、ダイナミックなキャラクターモーションと強烈な色彩設計が炸裂。ずとまよ×Wabokuのコンビは国内アニメーションMVシーン屈指のクオリティを誇る。"
  },
  {
    id: "2026-05-22-jp-05",
    date: "2026-05-22",
    region: "jp",
    title: "YOASOBI「New me」Official Music Video",
    creator: "YOASOBI / Havtza / pH Studio",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=HRlW6yZo6Kc",
    creatorUrl: "https://www.youtube.com/@YOASOBI_staff",
    articleUrl: "https://www.anitrendz.com/news/2024/11/30/yoasobi-releases-new-me-anime-music-video",
    publishedDate: "2024-11-30",
    genre: ["MV", "アニメーション"],
    techniques: ["2Dアニメーション", "Vector"],
    thumbnail: "https://img.youtube.com/vi/HRlW6yZo6Kc/mqdefault.jpg",
    notes: "Recruit CMソング発のアニメMV。監督Havtzaがコンセプト・キャラクターデザイン・演出を一手に担いpH Studioが制作。鮮やかなカラーパレットとキネティックな2Dアニメーションの流れが国際的にも高い評価を獲得し、YOASOBIのグローバル進出を象徴する一作。"
  },
  {
    id: "2026-05-22-global-01",
    date: "2026-05-22",
    region: "global",
    title: "Trails Will Blaze — BBC Winter Olympics 2026",
    creator: "NOMINT / BBC Creative",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1158419326",
    creatorUrl: "https://vimeo.com/nomint",
    articleUrl: "https://stopmotionmagazine.com/bbc-trails-will-blaze-stop-motion-winter-olympics-2026/",
    publishedDate: "2026-02-13",
    genre: ["CM", "タイトル/OP"],
    techniques: ["ストップモーション", "実写合成"],
    thumbnail: "https://vumbnail.com/1158419326.jpg",
    notes: "ミラノ・コルティナ2026冬季五輪のBBCトレーラー。700体の3Dプリント選手フィギュアに実火を用いたストップモーション撮影で制作。イタリア・ドロミテの縮小模型を舞台にVerdiの「レクイエム」をBBC交響楽団がライブ録音。Motionographer採点8.62超えの2026年上半期最高傑作。"
  },
  {
    id: "2026-05-22-global-02",
    date: "2026-05-22",
    region: "global",
    title: "BMW Heart of Joy — Meet Okto the Octopus",
    creator: "Untold Studios / Jung von Matt",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=t4tO5htFvpc",
    creatorUrl: "https://www.untoldstudios.com/",
    articleUrl: "https://www.stashmedia.tv/dancing-with-myself-okto-the-octopus-oscillates-for-bmw/",
    publishedDate: "2025-06-17",
    genre: ["CM", "3DCG"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/t4tO5htFvpc/mqdefault.jpg",
    notes: "タコの分散神経系＝BMW次世代中央制御ユニットというアナロジーから生まれたCMキャラクター「Okto」。南アフリカ実写水中映像へのフルCG合成のクオリティが圧巻。2026 VES Awards Outstanding Visual Effects / Compositing 受賞、Webbyアワードベストアニメーション・モーショングラフィクス受賞。"
  },
  {
    id: "2026-05-22-global-03",
    date: "2026-05-22",
    region: "global",
    title: "Finch — Whatever It Takes to Get Through the Day",
    creator: "Kirsten Lepore / Mathematic",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Har-tUpSmmU",
    creatorUrl: "https://mathematic.tv/",
    articleUrl: "https://adage.com/creativity/creative-strategy-tactics/aa-finch-whatever-it-takes-to-get-through-the-day/",
    publishedDate: "2026-05-21",
    genre: ["CM", "アニメーション"],
    techniques: ["3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/Har-tUpSmmU/mqdefault.jpg",
    notes: "セルフケアアプリFinchのファーストブランドキャンペーン（5/21公開・昨日リリース）。Oscar ノミネート＆Emmy 受賞監督Kirsten Lepore（Mathematic）が手がけた90秒アニメミュージカル。ケーキをむさぼる・怒りの雑巾がけ・剣で枕を叩き割るなど『何とかやり過ごす日々』の滑稽さを愛らしく描く。"
  },
  {
    id: "2026-05-22-global-04",
    date: "2026-05-22",
    region: "global",
    title: "Squarespace — Blueprint AI",
    creator: "ManvsMachine",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1068776467",
    creatorUrl: "https://mvsm.com/",
    articleUrl: "https://lbbonline.com/news/squarespace-introduces-its-ai-website-builder-with-a-human-touch",
    publishedDate: "2025-03-25",
    genre: ["CM", "ブランディング"],
    techniques: ["モーフィング", "実写合成"],
    thumbnail: "https://vumbnail.com/1068776467.jpg",
    notes: "Squarespace AIウェブビルダー「Blueprint AI」のローンチCM。デザイナーのスケッチブック上のアイデアが実際に飛び出し、デジタルUIへ変換される様子を実写＋モーショングラフィクスで表現。ManvsMachineらしいエレガントなトランジションと精緻な質感設計が際立つブランドフィルム。"
  },
  {
    id: "2026-05-22-global-05",
    date: "2026-05-22",
    region: "global",
    title: "HAG — Official Trailer",
    creator: "Anna Ginsburg / Strange Beast / Passion Pictures",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1113936655",
    creatorUrl: "https://www.strangebeast.tv/",
    articleUrl: "https://lbbonline.com/news/Passion-Pictures-and-Strange-Beast-Win-at-SXSW-2026",
    publishedDate: "2025-11-15",
    genre: ["アニメーション", "実験的"],
    techniques: ["2Dアニメーション", "モーフィング"],
    thumbnail: "https://vumbnail.com/1113936655.jpg",
    notes: "SXSW 2026アニメーション部門Special Jury Award受賞の短編。別れ・生物時計・家父長制の圧力をダークコメディで描いたBFI出資作品。Anna Ginsburgの独自キャラクターデザインと大胆な色使い、メタモルフォーゼ的アニメーションが強烈な印象を残す。現在国際フェスティバル巡回中。"
  },
  // ===== 2026-05-21 =====
  {
    id: "2026-05-21-jp-01",
    date: "2026-05-21",
    region: "jp",
    title: "AFEELA Prototype 2026 | Concept Movie",
    creator: "WOW inc. / Sony Honda Mobility",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=tMkmiZS0brQ",
    creatorUrl: "https://www.w0w.co.jp/en/",
    articleUrl: "https://www.shm-afeela.com/en/news/2026-01-06/",
    publishedDate: "2026-01-06",
    genre: ["ブランディング", "3DCG"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "https://img.youtube.com/vi/tMkmiZS0brQ/mqdefault.jpg",
    notes: "ソニー・ホンダモビリティのEV『AFEELA』がCES 2026でワールドプレミアした際の公式コンセプトムービー。東京のビジュアルデザインスタジオWOW inc.が手がけた3DCGと動的UIアニメーションの融合映像で、車体フォルムとデジタルインターフェースが有機的に絡み合う。モビリティの未来を高い審美眼で提示した意欲的なブランドフィルム。"
  },
  {
    id: "2026-05-21-jp-02",
    date: "2026-05-21",
    region: "jp",
    title: "MULTRA Brand Film",
    creator: "MULTRA Inc.",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1135619204",
    creatorUrl: "https://vimeo.com/multra",
    articleUrl: "https://www.stashmedia.tv/multra-studio-makes-stash-debut-with-new-brand-film/",
    publishedDate: "2025-10-01",
    genre: ["ブランディング", "モーショングラフィクス"],
    techniques: ["2Dアニメーション", "モーフィング"],
    thumbnail: "https://vumbnail.com/1135619204.jpg",
    notes: "東京のモーションデザインスタジオMULTRAによるSTASHデビュー自主制作ブランドフィルム。ジャズィーなリズムとともに多様なクリエイティブアイデアが連続・変容するマルチメディア表現。手描きキャラクターとグラフィックモーションがシームレスに融合し、スタジオのクリエイティブDNAを余すところなく体現する。"
  },
  {
    id: "2026-05-21-jp-03",
    date: "2026-05-21",
    region: "jp",
    title: "パワフルプロ野球2026-2027 オープニングムービー",
    creator: "KOO-KI x Konami Digital Entertainment",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=wOjrANePk1c",
    creatorUrl: "https://koo-ki.co.jp/",
    articleUrl: "https://koo-ki.co.jp/works/detail/pawa-2026-2027",
    publishedDate: "2026-03-12",
    genre: ["タイトル/OP", "3DCG"],
    techniques: ["3DCG", "2Dアニメーション"],
    thumbnail: "https://img.youtube.com/vi/wOjrANePk1c/mqdefault.jpg",
    notes: "野球ゲームシリーズ30周年を飾るオープニングムービー。福岡の映像集団KOO-KIが歴代WBC名場面をリイマジネーションし、イチロー・大谷翔平ら伝説的選手が集結するダイナミックな3DCGシーンを展開。スポーツゲームOPの域を超えた映像クオリティは国内外のゲームファン・映像ファンから高い評価を受ける。"
  },
  {
    id: "2026-05-21-jp-04",
    date: "2026-05-21",
    region: "jp",
    title: "HIDARI（ひだり） - ストップモーション侍映画 パイロット版",
    creator: "Whatever Co. / dwarf studios / TECARAT（川村真司監督）",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=DpefYPLH67A",
    creatorUrl: "https://whatever.co/work/hidari/",
    articleUrl: "https://variety.com/2026/film/global/keanu-reeves-voice-lead-stop-motion-samurai-film-hidari-1236751402/",
    publishedDate: "2023-03-27",
    genre: ["アニメーション"],
    techniques: ["ストップモーション"],
    thumbnail: "https://img.youtube.com/vi/DpefYPLH67A/mqdefault.jpg",
    notes: "全キャラクターを木から手彫りしフレームごとに動かすストップモーション時代劇の短編パイロット版。4.9M再生を突破し2026年5月カンヌAnnecy Showcaseへ選出。同月キアヌ・リーブスのリード声優起用が発表され再び世界から注目を集めた、日本の手仕事アニメーションの金字塔。"
  },
  {
    id: "2026-05-21-jp-05",
    date: "2026-05-21",
    region: "jp",
    title: "Ado「ビバリウム」Official Music Video",
    creator: "林響太朗 / ACROBAT FILM",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=YvYii6dluM8",
    creatorUrl: "https://www.universal-music.co.jp/ado/",
    articleUrl: "https://natalie.mu/music/news/662104",
    publishedDate: "2026-02-28",
    genre: ["MV"],
    techniques: ["実写合成"],
    thumbnail: "https://img.youtube.com/vi/YvYii6dluM8/mqdefault.jpg",
    notes: "Ado初の完全実写MV。自身の半生をテーマにした楽曲に合わせ林響太朗監督が300カット超の迫力映像を構築した意欲作。水中撮影・逆光シルエット・ハイヒール疾走など多彩な手法を組み合わせ、Adoの感情の振れ幅を余すところなく映像化。日本音楽MVの新境地として各メディアが絶賛した2026年の注目作。"
  },
  {
    id: "2026-05-21-global-01",
    date: "2026-05-21",
    region: "global",
    title: "Coinbase — System Update",
    creator: "BUCK / Isle of Any",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=SemnKhDNZVU",
    creatorUrl: "https://buck.co/work/coinbase-system-update",
    articleUrl: "https://www.stashmedia.tv/buck-cracks-the-code-for-coinbase/",
    publishedDate: "2025-05-07",
    genre: ["CM", "ブランディング"],
    techniques: ["2Dアニメーション", "タイポグラフィ"],
    thumbnail: "https://img.youtube.com/vi/SemnKhDNZVU/mqdefault.jpg",
    notes: "ASCIIアートと2Dアニメーションを融合させたCoinbaseのブランドアンセムフィルム。旧来の銀行システムの『ブルースクリーン・オブ・デス』から始まりCoinbase主導の新世界への再起動を描く。Houdini・C4D・Cavalry・After Effectsを駆使した技術的にも先鋭的な映像はNBAプレーオフ初放映で400万超視聴、D&ADアワードも受賞。"
  },
  {
    id: "2026-05-21-global-02",
    date: "2026-05-21",
    region: "global",
    title: "Affinity — Creative Freedom",
    creator: "ManvsMachine / Canva",
    platform: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=CzPzRxDoirM",
    creatorUrl: "https://mvsm.com/project/canva-affinity",
    articleUrl: "https://www.stashmedia.tv/zero-bucks-given-manvsmachine-keeps-it-kinetic-for-canva/",
    publishedDate: "2025-11-07",
    genre: ["CM", "ブランディング"],
    techniques: ["3DCG", "2Dアニメーション", "キネティックタイポ"],
    thumbnail: "https://img.youtube.com/vi/CzPzRxDoirM/mqdefault.jpg",
    notes: "Canvaが完全無料化したデザインツール『Affinity』ローンチを飾るブランドキャンペーン映像。ManvsMachineが3D・2Dモーション・キネティックタイポグラフィ・手描きイラストを縦横無尽に融合させ、クリエイターへの解放宣言を表現したパワフルなハイプフィルム。1週間で100万人登録突破を達成した歴史的プロダクトローンチの象徴的映像。"
  },
  {
    id: "2026-05-21-global-03",
    date: "2026-05-21",
    region: "global",
    title: "NBC Primetime in Milan — Winter Olympics 2026 Title Sequence",
    creator: "Imaginary Forces",
    platform: "Vimeo",
    videoUrl: "https://imaginaryforces.com/project/winter-olympic-games-milan-cortina-2026",
    creatorUrl: "https://imaginaryforces.com/",
    articleUrl: "https://www.nbcsports.com/pressbox/press-releases/nbc-sports-selected-imaginary-forces-to-create-cinematic-main-title-sequence-for-primetime-in-milan",
    publishedDate: "2026-02-06",
    genre: ["タイトル/OP"],
    techniques: ["3DCG", "実写合成"],
    thumbnail: "",
    notes: "ミラノ・コルティナ2026冬季五輪のNBC『Primetime in Milan』用メインタイトルシーケンス。ILM StageCraftのボリュメトリックスクリーンを用いた実写撮影と3DCGを融合させ、イタリアの冬景色の中でチームUSAの歴代名場面を描く。Imaginary Forcesが五輪タイトルの信頼を再び示した、ブロードキャストデザインの到達点。"
  },
  {
    id: "2026-05-21-global-04",
    date: "2026-05-21",
    region: "global",
    title: "Telstra — Outback to Orbit | Satellite Messaging Campaign",
    creator: "Passion Animation / Bear Meets Eagle On Fire",
    platform: "Vimeo",
    videoUrl: "https://www.creativereview.co.uk/telstra-satellite-messaging-stop-motion-campaign/",
    creatorUrl: "https://www.passion-animation.com/director/catherine-prowse/",
    articleUrl: "https://www.stashmedia.tv/heres-how-catherine-prowse-passion-animation-built-stop-motion-messaging-for-telstra/",
    publishedDate: "2026-04-15",
    genre: ["CM"],
    techniques: ["ストップモーション"],
    thumbnail: "",
    notes: "オーストラリアの通信会社Telstraのサテライトメッセージ機能を訴求した3部作ストップモーションCM。農場・砂漠・山岳のセットが物理的に回転しながら宇宙への接続を描く独創的なメカニズムが秀逸。Catherine Prowse（Passion Animation）が緻密な模型制作と撮影で実現した、2026年の傑作ストップモーションCMとして各メディアが絶賛。"
  },
  {
    id: "2026-05-21-global-05",
    date: "2026-05-21",
    region: "global",
    title: "OFFF Barcelona 2026 — Official Aftermovie",
    creator: "OFFF Festival",
    platform: "Vimeo",
    videoUrl: "https://vimeo.com/1189630992",
    creatorUrl: "https://www.offf.barcelona/",
    articleUrl: "https://motionographer.com/news/offf-2026-returns-for-26th-year-in-celebration-of-creativity-art-and-design/",
    publishedDate: "2026-04-30",
    genre: ["モーショングラフィクス", "タイトル/OP"],
    techniques: ["タイポグラフィ", "実写合成"],
    thumbnail: "https://vumbnail.com/1189630992.jpg",
    notes: "デザイン・アニメーション・映像の世界的祭典OFFF Barcelona 2026（第26回）のオフィシャルアフタームービー。76カ国・5,500名/日が集結した会期の全容を収録し、Laundry Studiosによるメインタイトルや多数のスピーカー登壇映像も収められる。モーションデザイン業界の最前線を一度に体感できる、フェスティバルの記念碑的アーカイブ映像。"
  },
];
